"""Submission item status class.

Manages the item status
"""
from __future__ import annotations

import enum


class ItemStatus(enum.Enum):
    """Enum for item statuses."""

    NEW_SUBMISSION = 'NEW_SUBMISSION'
    PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED'
    COMPLETED = 'COMPLETED'
    SUBMITTED = 'SUBMITTED'
    PASSED_CONSULTATION_CHECK = 'PASSED_CONSULTATION_CHECK'
    UNDER_REVIEW = 'UNDER_REVIEW'
    UNDER_CONSULTATION_CHECK = 'UNDER_CONSULTATION_CHECK'
    REVIEW_REJECTED = 'REVIEW_REJECTED'
    APPROVED = 'APPROVED'
    ACCEPTED = 'ACCEPTED'
    SATISFIED = 'SATISFIED'
    AWAITING_MANAGER_REVIEW = 'AWAITING_MANAGER_REVIEW'
    CC_AWAITING_MANAGER_REVIEW = 'CC_AWAITING_MANAGER_REVIEW'
    MP_AWAITING_MANAGER_REVIEW = 'MP_AWAITING_MANAGER_REVIEW'
    REVISION_REQUIRED = 'REVISION_REQUIRED'
