replicaCount: 2

image:
  repository: image-registry.openshift-image-registry.svc:5000/c72cba-tools/submit-api
  pullPolicy: Always
  tag: "prod"

resources:
  cpu:
    limit: 750m
    request: 700m
  memory:
    limit: 938Mi
    request: 836Mi

database:
  secret: submit-patroni
  service:
    name: submit-patroni
    port: 5432
  demo:
    enabled: false
    suffix: demo

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

auth:
  jwt:
    alg: RS256
    aud: epic-submit
    cacheEnabled: true
    issuer: https://loginproxy.gov.bc.ca/auth/realms/eao-epic
    cacheTimeout: "300"
    wellKnownConfig: https://loginproxy.gov.bc.ca/auth/realms/eao-epic/.well-known/openid-configuration
  keycloak:
    uri: https://loginproxy.gov.bc.ca
    realm: eao-epic
  serviceAccount:
    id: ""
    secret: ""
  epicAuth:
    baseUrl: https://auth-api-c72cba-prod.apps.gold.devops.gov.bc.ca

python:
  pythonBuffered: 1
  connectTimeout: 60

cors:
  origin: "https://submit.eao.gov.bc.ca,"

web:
  url: https://submit.eao.gov.bc.ca

sender:
  email: EAO.ManagementPlanSupport@gov.bc.ca

staffSupportMailId: EAO.ManagementPlanSupport@gov.bc.ca

signupUrlPath: /proponent/account-registration

documentService:
  url: https://epic-document-api-c8b80a-prod.apps.gold.devops.gov.bc.ca/api

geo:
  maxConcurrentJobs: "4"
  maxShapefiles: "40"
  processingTimeoutSeconds: "60"

timezone: US/Pacific
