replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/c8b80a-tools/submit-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

resources:
  cpu:
    limit: 100m
    request: 75m
  memory:
    limit: 384Mi
    request: 256Mi

database:
  secret: submit-patroni
  service:
    name: submit-patroni
    port: 5432
  demo:
    enabled: false
    suffix: demo
    username: ""
    password: ""
    name: ""

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

auth:
  jwt:
    alg: RS256
    aud: epic-submit
    cacheEnabled: true
    issuer: https://dev.loginproxy.gov.bc.ca/auth/realms/eao-epic
    cacheTimeout: "300"
    wellKnownConfig: https://dev.loginproxy.gov.bc.ca/auth/realms/eao-epic/.well-known/openid-configuration
  keycloak:
    uri: https://dev.loginproxy.gov.bc.ca
    realm: eao-epic
    instanceAdminGroup: INSTANCE_ADMIN
    adminClientId:
    adminClientSecret:
  epicAuth:
    baseUrl: http://epic-auth-api:8080
python:
  pythonBuffered: 1
  connectTimeout: 60
cors:
  origin: "https://dev.submit.eao.gov.bc.ca,"

web:
  url: https://dev.submit.eao.gov.bc.ca

sender:
  email: EAO.ManagementPlanSupport@gov.bc.ca

bcServiceCard:
  url: https://id.gov.bc.ca

timezone: US/Pacific
