{{- if .Values.chesSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: ches-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  CHES_TOKEN_ENDPOINT: {{ .Values.chesSecrets.tokenEndPoint | b64enc }}
  CHES_BASE_URL: {{ .Values.chesSecrets.apiEndPoint | b64enc }}
  CHES_CLIENT_ID: {{ .Values.chesSecrets.clientId | b64enc }}
  CHES_CLIENT_SECRET: {{ .Values.chesSecrets.clientSecret | b64enc }}
{{- end }}
