{{- if .Values.chesSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: ches-secrets
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  CDOGS_TOKEN_END_POINT: {{ .Values.chesSecrets.tokenEndPoint | b64enc }}
  CDOGS_API_ENDPOINT: {{ .Values.chesSecrets.apiEndPoint | b64enc }}
  CDOGS_CLIENT_ID: {{ .Values.chesSecrets.clientId | b64enc }}
  CDOGS_CLIENT_SECRET: {{ .Values.chesSecrets.clientSecret | b64enc }}
{{- end }}
