apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app-group: submit-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app-group: submit-app
        environment: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: image-registry.openshift-image-registry.svc:5000/{{ .Values.imageNamespace }}/{{ .Values.name }}:{{ .Values.imageTag }}
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: cron-config
              mountPath: /submit-cron/cron/
              readOnly: true
          env: # same as above
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DATABASE_NAME
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DATABASE_PORT
            - name: CENTRE_DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: CENTRE_DATABASE_USERNAME
            - name: CENTRE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: CENTRE_DATABASE_PASSWORD
            - name: CENTRE_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: CENTRE_DATABASE_NAME
            - name: CENTRE_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: CENTRE_DATABASE_HOST
            - name: CENTRE_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: CENTRE_DATABASE_PORT
            - name: CHES_TOKEN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: ches-secrets
                  key: CHES_TOKEN_ENDPOINT
            - name: CHES_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ches-secrets
                  key: CHES_BASE_URL
            - name: CHES_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ches-secrets
                  key: CHES_CLIENT_ID
            - name: CHES_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ches-secrets
                  key: CHES_CLIENT_SECRET
            - name: WEB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: WEB_URL
            - name: SENDER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: SENDER_EMAIL
            - name: STAFF_SUPPORT_MAIL_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: STAFF_SUPPORT_MAIL_ID
            - name: KEYCLOAK_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: KEYCLOAK_BASE_URL
            - name: KEYCLOAK_REALM_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: KEYCLOAK_REALM_NAME
            - name: KEYCLOAK_SERVICE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: KEYCLOAK_SERVICE_ACCOUNT_ID
            - name: KEYCLOAK_SERVICE_ACCOUNT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: KEYCLOAK_SERVICE_ACCOUNT_SECRET
            - name: CONDITION_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: CONDITION_API_BASE_URL
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
      volumes:
        - name: cron-config
          configMap:
            name: {{ .Release.Name }}-config
            defaultMode: 420
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
