apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
stringData:
  KEYCLOAK_SERVICE_ACCOUNT_ID: {{ .Values.keycloak.serviceAccountId }}
  KEYCLOAK_SERVICE_ACCOUNT_SECRET: {{ .Values.keycloak.serviceAccountSecret }}
 