name: submit-cron
imageNamespace: c8b80a-tools
env: dev
database:
  host: submit-patroni
  port: "5432"
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 250m
    memory: 200Mi
replicaCount: 1
imageTag: dev

cronTab: "*/5 * * * * default cd /submit-cron && ./run_emailer.sh"


chesSecrets:
  create: true
  tokenEndPoint: "https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token"
  apiEndPoint: "https://ches-dev.api.gov.bc.ca"
  clientId: "CDACC9DF-F0E517FDED1"
  clientSecret: "5c3cd76e-f02c-4903-af8a-ed3c7b0c5372"
