"""add not_applicable to itemstatus

Revision ID: 00f63e6d1384
Revises: 861b5e7374e0
Create Date: 2026-06-11 16:28:46.704817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00f63e6d1384'
down_revision = '861b5e7374e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_project_non_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_project_non_works_account_project_id'))

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('project_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)

    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type typ 
                       JOIN pg_enum en ON en.enumtypid = typ.oid 
                       WHERE typ.typname = 'itemstatus' AND en.enumlabel = 'NOT_APPLICABLE') THEN
            ALTER TYPE itemstatus ADD VALUE 'NOT_APPLICABLE';
        END IF;
    END$$;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('project_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)

    with op.batch_alter_table('account_project_non_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_account_project_non_works_account_project_id'), ['account_project_id'], unique=False)

    # ### end Alembic commands ###
