""" Add user type column

Revision ID: 075df7d4f03b
Revises: 8e3b41ce9e50
Create Date: 2024-10-30 16:15:35.557115

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '075df7d4f03b'
down_revision = '8e3b41ce9e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    usertype_enum = sa.Enum('PROPONENT', 'STAFF', name='usertype')
    usertype_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', usertype_enum, nullable=True))

    # Get list of user_ids from account_users
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT user_id FROM account_users")).fetchall()
    user_ids = [row[0] for row in result]

    # Update user type to PROPONENT for all users in account_users if user_ids is not empty
    if user_ids:
        user_ids_str = ','.join(map(str, user_ids))
        op.execute(f"UPDATE users SET type = 'PROPONENT' WHERE id IN ({user_ids_str})")
    else:
        print("No user IDs found in account_users. Skipping update to PROPONENT.")

    # Update user type to STAFF for all users not in account_users if user_ids is not empty
    if user_ids:
        op.execute(f"UPDATE users SET type = 'STAFF' WHERE id NOT IN ({user_ids_str})")
    else:
        op.execute("UPDATE users SET type = 'STAFF'")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('type', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('type')

    # Drop the enum type
    usertype_enum = sa.Enum('PROPONENT', 'STAFF', name='usertype')
    usertype_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
