""" Add unique constraint to user_id column in staff_users table

Revision ID: 0b48adc3879f
Revises: 6b4eb077a447
Create Date: 2024-12-17 12:13:07.262209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b48adc3879f'
down_revision = '6b4eb077a447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_constraint', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_constraint', type_='unique')
    # ### end Alembic commands ###
