""" Add status column to update_requests

Revision ID: 1056f5daad12
Revises: a6aa74a8e7c4
Create Date: 2025-01-14 09:47:22.694555

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1056f5daad12'
down_revision = 'a6aa74a8e7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type
    op.execute("CREATE TYPE updaterequeststatus AS ENUM ('OPEN', 'PENDING_REVIEW', 'CLOSED')")

    # Add the column with a default value
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('OPEN', 'PENDING_REVIEW', 'CLOSED',
                                                        name='updaterequeststatus'), nullable=False,
                                      server_default='OPEN'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.drop_column('status')
    # Drop the enum type
    op.execute("DROP TYPE updaterequeststatus")
    # ### end Alembic commands ###

