"""Remove unique constraint from proponent_id in projects

Revision ID: 1839037128e2
Revises: 7ea1ebf27b4e
Create Date: 2025-08-06 10:05:05.444123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1839037128e2'
down_revision = '7ea1ebf27b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('projects_proponent_id_key', type_='unique')
        batch_op.create_index('ix_projects_proponent_id', ['proponent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_proponent_id')
        batch_op.create_unique_constraint('projects_proponent_id_key', ['proponent_id'])

    # ### end Alembic commands ###
