"""

Revision ID: 1e9b19ace1fa
Revises: 0b48adc3879f
Create Date: 2024-12-20 16:19:57.674503

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e9b19ace1fa"
down_revision = "0b48adc3879f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("review_start_date", sa.DateTime(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("review_start_date")
    # ### end Alembic commands ###
