""" Add submission_item_types column to update_requests

Revision ID: 1f4745895453
Revises: 56adb905f820
Create Date: 2025-02-13 13:27:30.319885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f4745895453'
down_revision = '56adb905f820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_item_types', sa.ARRAY(sa.Integer()), nullable=False))
        batch_op.drop_column('submission_item_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_item_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
        batch_op.drop_column('submission_item_types')
    # ### end Alembic commands ###
