""" add user table

Revision ID: 20a2b81fe5f7
Revises: e1e1b81ad5c8
Create Date: 2024-10-30 12:56:44.220088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a2b81fe5f7'
down_revision = 'e1e1b81ad5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_guid', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_guid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_auth_guid', ['auth_guid'], unique=True)

    # populate auth_guid, created_Date, updated_date, created_by, updated_by from account_users
    op.execute("INSERT INTO users (auth_guid, created_date, updated_date, created_by, updated_by) SELECT auth_guid, created_date, updated_date, created_by, updated_by FROM account_users")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_auth_guid')

    op.drop_table('users')
    # ### end Alembic commands ###
