"""unique constraint account project

Revision ID: 2656a9b67883
Revises: e9ede8ab9185
Create Date: 2026-02-02 09:38:20.712941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2656a9b67883'
down_revision = 'e9ede8ab9185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename existing submissiontypestatus to submissiontype (used by type column)
    op.execute("ALTER TYPE submissiontypestatus RENAME TO submissiontype")
    
    # Create new submissiontypestatus enum for status column
    op.execute("CREATE TYPE submissiontypestatus AS ENUM ('SUBMITTED', 'REJECTED', 'APPROVED', 'PENDING', 'PENDING_REPLACEMENT')")
    
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        # Change status column from submissionstatus to submissiontypestatus
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('SUBMITTED', 'REJECTED', 'APPROVED', 'PENDING', 'PENDING_REPLACEMENT', name='submissionstatus'),
               type_=sa.Enum('SUBMITTED', 'REJECTED', 'APPROVED', 'PENDING', 'PENDING_REPLACEMENT', name='submissiontypestatus'),
               existing_nullable=True,
               postgresql_using='status::text::submissiontypestatus')
    
    with op.batch_alter_table('account_projects', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_account_project', ['account_id', 'project_id'])
    
    # Drop old unused enum type
    op.execute("DROP TYPE IF EXISTS submissionstatus")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the old enum type
    op.execute("CREATE TYPE submissionstatus AS ENUM ('SUBMITTED', 'REJECTED', 'APPROVED', 'PENDING', 'PENDING_REPLACEMENT')")
    
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        # Revert status column from submissiontypestatus back to submissionstatus
        batch_op.alter_column('status',
               existing_type=sa.Enum('SUBMITTED', 'REJECTED', 'APPROVED', 'PENDING', name='submissiontypestatus'),
               type_=postgresql.ENUM('SUBMITTED', 'REJECTED', 'APPROVED', 'PENDING', 'PENDING_REPLACEMENT', name='submissionstatus'),
               existing_nullable=True,
               postgresql_using='status::text::submissionstatus')
    
    with op.batch_alter_table('account_projects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_account_project', type_='unique')
    
    # Drop the enum type created in upgrade and rename submissiontype back
    op.execute("DROP TYPE IF EXISTS submissiontypestatus")
    op.execute("ALTER TYPE submissiontype RENAME TO submissiontypestatus")

    # ### end Alembic commands ###
