"""update_submission_item_status

Revision ID: 30d03b77c562
Revises: dfd81c02e843
Create Date: 2025-05-08 13:00:33.757510

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '30d03b77c562'
down_revision = 'b92c15f6a7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE submissionstatus ADD VALUE 'PENDING_REPLACEMENT'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
