"""update original submission text

Revision ID: 32778cbd0c4a
Revises: 4f8c0a55cb6a
Create Date: 2025-05-29 03:52:18.622018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32778cbd0c4a'
down_revision = '4f8c0a55cb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Update activity log actions to replace "Original Submission" with "Submitted to EAO"
    op.execute("""
        UPDATE activity_logs
        SET action = 'Submitted to EAO'
        WHERE action = 'Original Submission';
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the action change in case of downgrade
    op.execute("""
        UPDATE activity_logs
        SET action = 'Original Submission'
        WHERE action = 'Submitted to EAO';
    """)
    # ### end Alembic commands ###
