"""update_status_to_upper_case

Revision ID: 3eab559030cf
Revises: e1a4440eb1ce
Create Date: 2025-04-01 11:27:24.837930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '3eab559030cf'
down_revision = 'e1a4440eb1ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    invitations = table(
        'invitations',
        column('id', sa.Integer),
        column('status', sa.String(50))
    )

    # Update all status values to uppercase
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT DISTINCT status FROM invitations"))
    statuses = [row[0] for row in result]

    for status in statuses:
        if status:
            conn.execute(
                invitations.update().where(invitations.c.status == status).values(status=status.upper())
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    invitations = table(
        'invitations',
        column('id', sa.Integer),
        column('status', sa.String(50))
    )

    # Update all status values to lowercase
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT DISTINCT status FROM invitations"))
    statuses = [row[0] for row in result]

    for status in statuses:
        if status:
            conn.execute(
                invitations.update().where(invitations.c.status == status).values(status=status.lower())
            )

    # ### end Alembic commands ###
