"""package_type_fields added

Revision ID: 45ae89dd3b17
Revises: e77a59c88dac
Create Date: 2026-04-20 10:50:39.097201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ae89dd3b17'
down_revision = 'e77a59c88dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default to handle existing rows
    with op.batch_alter_table('package_item_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_required', sa.Boolean(), nullable=False, server_default='true', comment='Whether this item type is required for the package type'))

    with op.batch_alter_table('package_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('versioning_enabled', sa.Boolean(), nullable=False, server_default='true', comment='Whether this package type supports versioning'))
        batch_op.add_column(sa.Column('mandatory', sa.Boolean(), nullable=False, server_default='false', comment='Whether this package type must be created by the system'))

    # Set versioning_enabled=false for Additional Information package type
    op.execute("""
        UPDATE package_types 
        SET versioning_enabled = false 
        WHERE name = 'Additional Information'
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_types', schema=None) as batch_op:
        batch_op.drop_column('mandatory')
        batch_op.drop_column('versioning_enabled')

    with op.batch_alter_table('package_item_types', schema=None) as batch_op:
        batch_op.drop_column('is_required')

    # ### end Alembic commands ###
