""" Add cascade delete to foreign keys

Revision ID: 4b571b0106cc
Revises: 7eeeaf8bc7d2
Create Date: 2025-12-26 13:51:14.367625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b571b0106cc'
down_revision = '7eeeaf8bc7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # internal_staff_documents.package_id → packages.id
    op.drop_constraint('internal_staff_documents_package_id_fkey', 'internal_staff_documents', type_='foreignkey')
    op.create_foreign_key('internal_staff_documents_package_id_fkey', 'internal_staff_documents', 'packages', ['package_id'], ['id'], ondelete='CASCADE')

    # items.package_id → packages.id
    op.drop_constraint('items_package_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key('items_package_id_fkey', 'items', 'packages', ['package_id'], ['id'], ondelete='CASCADE')

    # package_metadata.package_id → packages.id
    op.drop_constraint('package_metadata_package_id_fkey', 'package_metadata', type_='foreignkey')
    op.create_foreign_key('package_metadata_package_id_fkey', 'package_metadata', 'packages', ['package_id'], ['id'], ondelete='CASCADE')

    # packages.account_project_id → account_projects.id
    op.drop_constraint('packages_account_project_id_fkey', 'packages', type_='foreignkey')
    op.create_foreign_key('packages_account_project_id_fkey', 'packages', 'account_projects', ['account_project_id'], ['id'], ondelete='CASCADE')

    # submission_item_notes.item_id → items.id
    op.drop_constraint('submission_item_notes_item_id_fkey', 'submission_item_notes', type_='foreignkey')
    op.create_foreign_key('submission_item_notes_item_id_fkey', 'submission_item_notes', 'items', ['item_id'], ['id'], ondelete='CASCADE')

    # submission_reviews.item_id → items.id
    op.drop_constraint('submission_reviews_item_id_fkey', 'submission_reviews', type_='foreignkey')
    op.create_foreign_key('submission_reviews_item_id_fkey', 'submission_reviews', 'items', ['item_id'], ['id'], ondelete='CASCADE')

    # update_requests.submission_package_id → packages.id
    op.drop_constraint('update_requests_submission_package_id_fkey', 'update_requests', type_='foreignkey')
    op.create_foreign_key('update_requests_submission_package_id_fkey', 'update_requests', 'packages', ['submission_package_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse all changes - remove CASCADE from constraints
    op.drop_constraint('update_requests_submission_package_id_fkey', 'update_requests', type_='foreignkey')
    op.create_foreign_key('update_requests_submission_package_id_fkey', 'update_requests', 'packages', ['submission_package_id'], ['id'])

    op.drop_constraint('submission_reviews_item_id_fkey', 'submission_reviews', type_='foreignkey')
    op.create_foreign_key('submission_reviews_item_id_fkey', 'submission_reviews', 'items', ['item_id'], ['id'])

    op.drop_constraint('submission_item_notes_item_id_fkey', 'submission_item_notes', type_='foreignkey')
    op.create_foreign_key('submission_item_notes_item_id_fkey', 'submission_item_notes', 'items', ['item_id'], ['id'])

    op.drop_constraint('packages_account_project_id_fkey', 'packages', type_='foreignkey')
    op.create_foreign_key('packages_account_project_id_fkey', 'packages', 'account_projects', ['account_project_id'], ['id'])

    op.drop_constraint('package_metadata_package_id_fkey', 'package_metadata', type_='foreignkey')
    op.create_foreign_key('package_metadata_package_id_fkey', 'package_metadata', 'packages', ['package_id'], ['id'])

    op.drop_constraint('items_package_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key('items_package_id_fkey', 'items', 'packages', ['package_id'], ['id'])

    op.drop_constraint('internal_staff_documents_package_id_fkey', 'internal_staff_documents', type_='foreignkey')
    op.create_foreign_key('internal_staff_documents_package_id_fkey', 'internal_staff_documents', 'packages', ['package_id'], ['id'])

    # ### end Alembic commands ###
