"""Add root_submission_id to submissions

Revision ID: 4dda18ca8bda
Revises: 56adb905f820
Create Date: 2025-02-13 12:55:14.310337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4dda18ca8bda'
down_revision = '1f4745895453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('submissions', sa.Column('root_submission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_submissions_root_submission',
        'submissions',
        'submissions',
        ['root_submission_id'],
        ['id']
    )


def downgrade():
    op.drop_constraint('fk_submissions_root_submission', 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'root_submission_id')