"""Add geo_data_uploads table

Revision ID: 4eab27236b2a
Revises: 77862b346adf
Create Date: 2026-03-19 11:37:00.995726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eab27236b2a'
down_revision = '77862b346adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_data_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.Column('raw_s3_key', sa.String(length=512), nullable=True),
    sa.Column('preview_s3_key', sa.String(length=512), nullable=True),
    sa.Column('standard_s3_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('geometry_type', sa.String(length=50), nullable=True),
    sa.Column('crs_original', sa.String(length=100), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo_data_uploads')
    # ### end Alembic commands ###
