"""account_terms_of_service

Revision ID: 4f8c0a55cb6a
Revises: 826fa830606a
Create Date: 2025-05-09 16:17:06.676534

"""
from alembic import op
from datetime import datetime
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f8c0a55cb6a'
down_revision = '826fa830606a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_terms_of_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rich_content', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    with op.batch_alter_table('account_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agreed_terms_of_service_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('terms_of_service_accepted_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            'fk_account_users_agreed_terms',
            'account_terms_of_service',
            ['agreed_terms_of_service_id'],
            ['id']
        )

    # load initial terms of agreement
    html_content = """<!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    <style>
        body {
        font-family: Arial, sans-serif;
        color: #003366;
        background-color: #ffffff;
        padding: 5px;
        }
        .container {
        max-width: 1343px;
        padding: 20px;
        }
        .content {
        font-size: 16px;
        line-height: 1.6;
        color: #333;
        text-align: left;
        }
        .cta-link {
        color: #1a5a96;
        font-weight: bold;
        text-decoration: none;
        }
    </style>
    </head>
    <body>
    <div class="container">
        <div class="content">
        <h1 class="cta-link">EPIC.submit Account Terms and Conditions</h1>
        <p>THE PARTIES to this Agreement are His Majesty the King in Right of the Province of British Columbia ("Province"), and the legal entity requesting an EPIC.submit Account ("Holder").</p>
        <p>WHEREAS:</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em;">
            A. The Environmental Assessment Office provides the EPIC.submit Service to allow Holders to submit various reports and records as required under the Environmental Assessment Act, S.B.C. 2018, c. 51.
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em;">
            B. EPIC.submit Accounts are comprised of (i) a Project Administrator Account that is specific to the Holder and (ii) any User Accounts created by the Project Administrator Account for specified individuals; and
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em;">
            C. The Holder wishes to obtain an EPIC.submit Account.
        </p>
        <p>NOW THEREFORE the parties agree as follows:</p>
        <p>WARRANTY</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            1. The Holder warrants that:
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            a) it has the power and capacity to accept, execute and deliver the Agreement;
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            b) if the Holder is not an individual, (i) the individual who executes the Agreement on the Holder’s behalf is authorized to do so by the Holder, and (ii) if the Holder is a corporation, that the individual who executes the Agreement on the Holder's behalf is authorized to do so by the Holder without affixing a traditional signature or the Holder's corporate seal; and
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            c) the Agreement is legally binding upon and enforceable against the Holder in accordance with its terms.
        </p>
        <p>AGREEMENT</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            2. The Holder is deemed to have accepted the terms and conditions of this Agreement, together with any applicable Schedules, by clicking the "I ACCEPT" icon located after the text of this Agreement. The Holder may request an EPIC.submit Account, and upon receipt of the request, the Province may, at its sole discretion, create an Account for the Holder. If the Province does not create an Account for the Holder, the Agreement is rescinded.
        </p>
        <p>DATA TRANSMISSION AND SUBMISSION ACKNOWLEDGEMENT</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            3. The Holder acknowledges that a submission through the EPIC.submit Service is not deemed received by the Province unless and until the Holder receives an explicit confirmation of receipt (e.g., confirmation number, acknowledgment email, or system-generated confirmation). The Province is not liable for any data that is lost, delayed, or corrupted in transit prior to such confirmation, and it is the Holder’s responsibility to ensure submissions are complete and properly acknowledged by the system.
        </p>
        <p>ACCESS</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            4. The Holder agrees that any individuals specified by the Holder to manage and access its EPIC.submit Account are authorized to act on behalf of the Holder for the relevant roles or functions (“Users”); and
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            5. The Holder is responsible for all activities performed by Users in utilizing the EPIC.submit Account.
        </p>
        <p>TERMS OF USE FOR USERS</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            6. The Holder will ensure that its Users abide by sections 6 to 9 of the Agreement.
        </p>
        <p>SECURITY</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            7. The Holder will adhere to all security policies, standards or procedures issued by the Province in relation to the EPIC.submit Service.
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            8. The Holder will not:
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            a) permit any third party to access its EPIC.submit Account, but may authorize a third party to be a User for the purpose of the third party providing services to the Holder, in which case the Holder acknowledges that it is responsible for the activities of any third party Users in accordance with paragraph 4 of this Agreement;
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            b) divulge, share or compromise its login IDs for the EPIC.submit Account;
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            c) attempt to defeat or compromise the security related to the EPIC.submit Service;
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            d) take any action that might reasonably be construed as altering, destroying or rendering ineffective the security related to the EPIC.submit Service; or
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            e) decompile, disassemble, reverse engineer, or otherwise copy any source code associated with the EPIC.submit Service.
        </p>
        <p>OWNERSHIP AND NON-PERMITTED USES</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        9. The Holder acknowledges and agrees that at all times the Province or its licensors are the owners of any software, hardware, servers, networks or other equipment used to provide the EPIC.submit Service to Holders.
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        10. The Holder will not take any action that would be inconsistent with or infringe any proprietary and intellectual property rights of the Province or its licensors to any software, hardware, servers, networks or other equipment, and to any documentation or information, used to provide the EPIC.submit Service to Holders.
        </p>
        <p>PRIVACY</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        11. The Account Holder assumes full responsibility for ensuring that the information provided by the Holder through the EPIC.submit Account does not include personal information as defined under the Freedom of Information and Protection of Privacy Act, R.S.B.C. 1996, c. 165.
        </p>
        <p>SUSPENSION OF SERVICE</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        12. The Holder agrees that the Province may suspend or cancel any Account at any time if:
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            a) a User has committed an act in contravention of sections 6 to 9 of the Agreement;
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            b) the Province deems such suspension or cancellation necessary for any good and valid reason.
        </p>
        <p>DURATION OF AGREEMENT</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        13. The Agreement will be in effect from the date of execution until terminated pursuant to the provisions of the Agreement.
        </p>
        <p>TERMINATION</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        14. The Province may terminate the Agreement:
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            a) if, in the Province's sole discretion, the Holder or a User breaches a term of the Agreement, immediately upon giving written notice of termination to the Holder; or
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            b) for any other reason, on giving at least 10 days' written notice of termination to the Holder.
        </p>
        <p>WAIVER</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        15. No failure or delay on the part of the Province to complain of an act or failure of the Holder or a User, or to declare the Holder or a User in breach of the Agreement will constitute a waiver by the Province of its rights.
        </p>
        <p>ASSIGNMENT AND SUBCONTRACTING</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        16. The Holder will not, without the prior written consent of the Province:
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            a) assign or transfer the Agreement or any of its rights under the Agreement; or
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            b) subcontract any obligation of the Holder under the Agreement.
        </p>
        <p>AMENDMENT</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        17. The Holder agrees that the Province may, at its sole discretion, amend the terms and conditions of the Agreement by providing notice of the revised Agreement to the Holder. Continued use of the EPIC.submit Account constitutes acceptance by the Holder of the revised Agreement.
        </p>
        <p>LIMITATION OF LIABILITY</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        18. THE PROVINCE WITH REGARD TO THE EPIC.SUBMIT SERVICE ASSUMES NO RESPONSIBILITY OR LIABILITY TO ANY PERSON USING THE EPIC.SUBMIT ACCOUNT OR ACCESSING ANY INFORMATION GENERATED THEREFROM, AND IN PARTICULAR:
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            a) in no event will the Province and its servants, agents, directors, contractors, and employees be liable for direct, indirect, general, special, or consequential damages including personal injury, lost profits, lost savings, or any other incidental damages arising out of the use of, or inability to use the EPIC.submit Service, or to utilize any information or data contained therein; and
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            b) the Province and its servants, agents, directors, contractors, and employees make no warranty or representation, either express or implied, with respect to the EPIC.submit Service, any information or data contained therein, or with respect to their performance, quality, merchantability, or fitness of the EPIC.submit Service for a particular purpose.
        </p>
        <p>INDEMNITY</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        19. The Holder indemnifies and saves harmless the Province and its servants, agents, directors, contractors, and employees (each an "Indemnified Person") against any and all losses, claims, damages, actions, causes of action, costs and expenses that an Indemnified Person may sustain, incur, suffer, or be put to by reason of an act or omission of the Holder or of its servants, agents, directors, contractors and employees, including by reason of the unauthorized release of information to third parties or the provision of incorrect, incomplete or misleading information to third parties, and the operation or failure of the Holder's computer hardware, software, or equipment.
        </p>
        <p>GENERAL</p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        20. Any notice, consent, waiver or other document referred to in the Agreement, to be effective, must be in writing and will be deemed validly given or delivered to and received by the addressee, if mailed then on the third business day after the mailing by prepaid post addressed, if sent by facsimile transmission then when so transmitted, or if sent by electronic mail then on entering an information system outside the control of the addressor,
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            if to the Province:
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            Email: EAOManagementPlanSupport@gov.bc.ca
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            Mailing Address: 301-836 Yates St, Victoria BC, V8V W1L8
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            and, if to the Holder:
        </p>
        <p style="padding-left: 40px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
            to the Holder's account manager at the address and email address specified in the Holder's request for an EPIC.submit Account.
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        21. The parties may give notice to the others of a substitute address, fax number, email address, or name or title of contact person from time to time.
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        22. The Agreement and any modification of it constitute the entire agreement between the parties.
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        23. The Schedules to the Agreement are part of the Agreement. In the event of a conflict or inconsistency between the Agreement and any terms and conditions specific to an e-Service as described in paragraph 6 of the Agreement, the terms and conditions of the Agreement prevail.
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        24. Time will be of the essence of the Agreement.
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        25. The Agreement will not in any way make the Holder or any User an employee, agent or independent contractor of the Province.
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        26. The Agreement will be for the benefit of and be binding upon the successors and permitted assigns of the Holder.
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        27. All provisions of the Agreement in favour of the Province, and all rights and remedies of the Province, either at law or in equity, will survive the termination of the Agreement.
        </p>
        <p style="padding-left: 20px; margin-left: 1.5em; text-indent: -1.5em; margin-top: 0; margin-bottom: 4px;">
        28. The Agreement is governed by and is to be construed in accordance with the laws of British Columbia.
        </p>
        </div>
    </div>
    </body>
    </html>
    """

    op.execute(
        text("""
            INSERT INTO account_terms_of_service (version, content, active, created_date)
            VALUES (:version, :content, :active, :created_date)
        """).bindparams(
            version=1,
            content=html_content.strip(),
            active=True,
            created_date=datetime.utcnow()
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_account_users_agreed_terms', type_='foreignkey')
        batch_op.drop_column('terms_of_service_accepted_date')
        batch_op.drop_column('agreed_terms_of_service_id')

    op.drop_table('account_terms_of_service')
    # ### end Alembic commands ###
