"""account_terms_of_service

Revision ID: 4f8c0a55cb6a
Revises: 826fa830606a
Create Date: 2025-05-09 16:17:06.676534

"""
import os
from alembic import op
from datetime import datetime
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f8c0a55cb6a'
down_revision = '826fa830606a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_terms_of_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rich_content', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    with op.batch_alter_table('account_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_of_service_version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('terms_of_service_accepted_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            'fk_account_users_agreed_terms',
            'account_terms_of_service',
            ['terms_of_service_version_id'],
            ['version']
        )

    # load initial terms of agreement
    dir_path = os.path.dirname(os.path.realpath(__file__))
    html_path = os.path.join(dir_path, '../templates/initial_terms_of_service.html')
    with open(html_path, encoding='utf-8') as f:
        html_content = f.read()

    op.execute(
        text("""
            INSERT INTO account_terms_of_service (version, content, active, created_date)
            VALUES (:version, :content, :active, :created_date)
        """).bindparams(
            version=1,
            content=html_content,
            active=True,
            created_date=datetime.utcnow()
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_account_users_agreed_terms', type_='foreignkey')
        batch_op.drop_column('terms_of_service_accepted_date')
        batch_op.drop_column('terms_of_service_version_id')

    op.drop_table('account_terms_of_service')
    # ### end Alembic commands ###
