""" Add PASSED_CONSULTATION_CHECK to packagestatus and itemstatus

Revision ID: 55762031c812
Revises: bb5eb7bffbed
Create Date: 2024-12-03 10:47:38.995844

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '55762031c812'
down_revision = 'bb5eb7bffbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$ 
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type typ 
                       JOIN pg_enum en ON en.enumtypid = typ.oid 
                       WHERE typ.typname = 'packagestatus' AND en.enumlabel = 'PASSED_CONSULTATION_CHECK') THEN
            ALTER TYPE packagestatus ADD VALUE 'PASSED_CONSULTATION_CHECK';
        END IF;
    END$$;
    """)
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type typ 
                       JOIN pg_enum en ON en.enumtypid = typ.oid 
                       WHERE typ.typname = 'itemstatus' AND en.enumlabel = 'PASSED_CONSULTATION_CHECK') THEN
            ALTER TYPE itemstatus ADD VALUE 'PASSED_CONSULTATION_CHECK';
        END IF;
    END$$;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
