""" Add new status values

Revision ID: 56adb905f820
Revises: 68b533d8d024
Create Date: 2025-02-07 15:50:28.634825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56adb905f820'
down_revision = '68b533d8d024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE packagestatus ADD VALUE IF NOT EXISTS 'APPROVED';")
    op.execute("ALTER TYPE itemstatus ADD VALUE IF NOT EXISTS 'APPROVED';")
    op.execute("ALTER TYPE packagestatus ADD VALUE IF NOT EXISTS 'ACCEPTED';")
    op.execute("ALTER TYPE itemstatus ADD VALUE IF NOT EXISTS 'ACCEPTED';")
    op.execute("ALTER TYPE packagestatus ADD VALUE IF NOT EXISTS 'SATISFIED';")
    op.execute("ALTER TYPE itemstatus ADD VALUE IF NOT EXISTS 'SATISFIED';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
