"""removed role from staff_user_work

Revision ID: 6319d2b3933e
Revises: c7f8a9b0e1d2
Create Date: 2026-07-02 14:59:53.575377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6319d2b3933e'
down_revision = 'c7f8a9b0e1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_user_works', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_user_works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Work role: TEAM_LEAD or TEAM_MEMBER'))

    # ### end Alembic commands ###
