""" Add submission_review_entries table

Revision ID: 640535864292
Revises: 79424fc490c5
Create Date: 2024-12-05 12:29:55.576075

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '640535864292'
down_revision = '79424fc490c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_review_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('STAFF_RECOMMENDATION', 'MANAGER_CONFIRMATION', name='submissionreviewentrytype'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('entry', sa.JSON(), nullable=False, server_default='{}'),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.auth_guid'], ),
    sa.ForeignKeyConstraint(['review_id'], ['submission_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_review_entries', schema=None) as batch_op:
        batch_op.create_index('review_submissions_review_id_idx', ['review_id'], unique=False)

    with op.batch_alter_table('submission_reviews', schema=None) as batch_op:
        batch_op.drop_column('form_answers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, server_default='{}'))

    with op.batch_alter_table('submission_review_entries', schema=None) as batch_op:
        batch_op.drop_index('review_submissions_review_id_idx')

    op.drop_table('submission_review_entries')
    # ### end Alembic commands ###
