""" Add AWAITING_MANAGER_REVIEW status to package and item

Revision ID: 705145d0cf36
Revises: 2a8e579da45c
Create Date: 2025-02-19 14:31:50.754640

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '705145d0cf36'
down_revision = '2a8e579da45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE packagestatus ADD VALUE IF NOT EXISTS 'AWAITING_MANAGER_REVIEW';")
    op.execute("ALTER TYPE itemstatus ADD VALUE IF NOT EXISTS 'AWAITING_MANAGER_REVIEW';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
