""" Add statuses column to items

Revision ID: 7838ee56a1c6
Revises: 87706710bc7c
Create Date: 2024-11-21 20:06:50.292349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7838ee56a1c6'
down_revision = '87706710bc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('statuses', sa.ARRAY(
        sa.Enum('NEW_SUBMISSION', 'PARTIALLY_COMPLETED', 'COMPLETED', 'SUBMITTED', name='itemstatus')), nullable=True))
    op.execute('UPDATE items set statuses = ARRAY[status::itemstatus]')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('statuses')
    # ### end Alembic commands ###
