""" Add status and active columns to submission_reviews

Revision ID: 7941b44f6927
Revises: 87706710bc7c
Create Date: 2024-11-26 13:46:10.424276

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '7941b44f6927'
down_revision = '87706710bc7c'
branch_labels = None
depends_on = None


def upgrade():
    # Create the enum type
    submissionreviewstatus_enum = sa.Enum('PENDING_STAFF_REVIEW', 'PENDING_MANAGER_REVIEW', 'APPROVED', 'REJECTED', name='submissionreviewstatus')
    submissionreviewstatus_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', submissionreviewstatus_enum, nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('submission_reviews_item_id_key', type_='unique')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('submission_reviews_item_id_key', ['item_id'])
        batch_op.drop_column('active')
        batch_op.drop_column('status')

    # Drop the enum type
    submissionreviewstatus_enum = sa.Enum('PENDING_STAFF_REVIEW', 'PENDING_MANAGER_REVIEW', 'APPROVED', 'REJECTED', name='submissionreviewstatus')
    submissionreviewstatus_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
