""" Add reviewed_on column to items, add json column to package_metadata

Revision ID: 79424fc490c5
Revises: 55762031c812
Create Date: 2024-12-03 10:52:30.764167

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '79424fc490c5'
down_revision = '55762031c812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_on', sa.DateTime(), nullable=True))

    with op.batch_alter_table('package_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json', sa.JSON()))
        batch_op.create_index('idx_package_id', ['package_id'], unique=False)
        batch_op.create_unique_constraint('package_metadata_package_id_uniquekey', ['package_id'])
        batch_op.drop_column('package_meta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False))
        batch_op.drop_constraint('package_metadata_package_id_uniquekey', type_='unique')
        batch_op.drop_index('idx_package_id')
        batch_op.drop_column('json')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('reviewed_on')
    # ### end Alembic commands ###
