""" Add version_id to packages

Revision ID: 7be2617a23a4
Revises: 94f284cada88
Create Date: 2025-01-17 15:14:03.542379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7be2617a23a4'
down_revision = '94f284cada88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'package_versions', ['version_id'], ['id'])

    # Update the version_id for each package
    op.execute("""
        UPDATE packages p
        SET version_id = (
            SELECT pv.id
            FROM package_versions pv
            WHERE pv.package_id = p.id
            ORDER BY pv.version DESC
            LIMIT 1
        )
    """)

    with op.batch_alter_table('package_versions', schema=None) as batch_op:
        batch_op.drop_index('idx_package_versions_package_id')
        batch_op.drop_constraint('package_versions_package_id_fkey', type_='foreignkey')
        batch_op.drop_column('package_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
