"""add_has_approved_condition_to_projects

Revision ID: 7ea1ebf27b4e
Revises: 7cadbb980cf7
Create Date: 2025-07-17 16:15:41.477386

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7ea1ebf27b4e'
down_revision = '7cadbb980cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_approved_condition', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('has_approved_condition')

    # ### end Alembic commands ###
