"""company_name in account_user

Revision ID: 7eeeaf8bc7d2
Revises: 471bff2fa76c
Create Date: 2025-12-22 16:41:16.606864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7eeeaf8bc7d2'
down_revision = '471bff2fa76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('internal_staff_documents', schema=None) as batch_op:
        batch_op.create_foreign_key('internal_staff_documents_created_by_fkey', 'users', ['created_by'], ['auth_guid'])

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.alter_column('project_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.create_unique_constraint("item_types_name_key", ['name'])

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_foreign_key('packages_submitted_by_fkey', 'users', ['submitted_by'], ['auth_guid'])

    with op.batch_alter_table('submission_review_entries', schema=None) as batch_op:
        batch_op.drop_constraint('submission_review_entries_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key("submission_review_entries_updated_by_fkey", 'users', ['updated_by'], ['auth_guid'])

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key("submissions_created_by_fkey", 'users', ['created_by'], ['auth_guid'])

    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('OPEN', 'PENDING_REVIEW', 'CLOSED', 'ACCEPTED', name='updaterequeststatus'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::updaterequeststatus"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('OPEN', 'PENDING_REVIEW', 'CLOSED', 'ACCEPTED', name='updaterequeststatus', create_type=False),
               existing_nullable=False,
               postgresql_using='status::updaterequeststatus',
               existing_server_default=sa.text("'OPEN'::updaterequeststatus"))


    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint("submissions_created_by_fkey", type_='foreignkey')
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.Enum('FORM', 'DOCUMENT', 'BUSINESS_DATA', name='submissiontype'),
               type_=postgresql.ENUM('FORM', 'DOCUMENT', 'BUSINESS_DATA', name='submissiontypestatus'),
               existing_nullable=False)

    with op.batch_alter_table('submission_review_entries', schema=None) as batch_op:
        batch_op.drop_constraint("submission_review_entries_updated_by_fkey", type_='foreignkey')
        batch_op.create_foreign_key('submission_review_entries_created_by_fkey', 'users', ['created_by'], ['auth_guid'])

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_constraint('packages_submitted_by_fkey', type_='foreignkey')

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.drop_constraint("item_types_name_key", type_='unique')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('project_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('internal_staff_documents', schema=None) as batch_op:
        batch_op.drop_constraint('internal_staff_documents_created_by_fkey', type_='foreignkey')

    with op.batch_alter_table('account_users', schema=None) as batch_op:
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
