"""Add is_first_time column to invitations

Revision ID: 8035b84066b2
Revises: fe3d9df59f7a
Create Date: 2025-03-17 15:07:44.448885

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8035b84066b2'
down_revision = 'fe3d9df59f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_first_time', sa.Boolean(), server_default=sa.text('false'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_column('is_first_time')

    # ### end Alembic commands ###
