"""Add root_submission_id column

Revision ID: 85b2825c9d10
Revises: 1f4745895453
Create Date: 2025-02-14 10:00:38.973943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85b2825c9d10'
down_revision = '1f4745895453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_submission_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'submissions', ['root_submission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('root_submission_id')
    # ### end Alembic commands ###
