"""create non canonical status table

Revision ID: 860b9deb7d0c
Revises: dfd81c02e843
Create Date: 2025-05-07 06:58:32.336199

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '860b9deb7d0c'
down_revision = 'dfd81c02e843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE noncanonicalpackagestatus AS ENUM ('UPDATED', 'UPDATE_REQUESTED');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
