"""Nonwork item related changes

Revision ID: 861b5e7374e0
Revises: e8e42981ee80
Create Date: 2026-06-03 19:17:06.030062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '861b5e7374e0'
down_revision = 'e8e42981ee80'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('account_project_non_works',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_project_id', sa.Integer(), nullable=False),
    sa.Column('non_work_item_type', sa.Enum('MANAGEMENT_PLAN', 'REPORT', name='nonworkitemtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['account_project_id'], ['account_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_project_id', 'non_work_item_type', name='uq_account_project_non_work')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_selections', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # Create index
    op.create_index('idx_account_project_non_works_account_project_id', 'account_project_non_works', ['account_project_id'])
    op.execute("""
        UPDATE invitations
        SET project_selections = (
            SELECT json_agg(
                json_build_object(
                    'project_id', pid,
                    'non_work_item_types', ARRAY['MANAGEMENT_PLAN']
                )
            )
            FROM unnest(project_ids) AS pid
        )
        WHERE project_selections IS NULL
        AND project_ids IS NOT NULL
        AND array_length(project_ids, 1) > 0
    """)
    
    # Make project_ids nullable for backward compatibility during transition
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('project_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_account_project_non_works_account_project_id', table_name='account_project_non_works')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_column('project_selections')

    op.drop_table('account_project_non_works')
    op.execute("DROP TYPE nonworkitemtype")
    op.execute("""
        UPDATE invitations
        SET project_ids = (
            SELECT array_agg(DISTINCT (ps->>'project_id')::integer)
            FROM json_array_elements(project_selections) AS ps
        )
        WHERE project_ids IS NULL
        AND project_selections IS NOT NULL
    """)
    
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('project_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    # ### end Alembic commands ###
