""" Add submission_reviews table

Revision ID: 87706710bc7c
Revises: df9c90534e9d
Create Date: 2024-11-21 11:18:56.311861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87706710bc7c'
down_revision = 'df9c90534e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('form_answers', sa.JSON(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    with op.batch_alter_table('submission_reviews', schema=None) as batch_op:
        batch_op.create_index('submission_reviews_item_id_idx', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_reviews', schema=None) as batch_op:
        batch_op.drop_index('submission_reviews_item_id_idx')
    op.drop_table('submission_reviews')
    # ### end Alembic commands ###
