"""staff user works table creation


Revision ID: 8b6bd8480abd
Revises: 5119a43fc059
Create Date: 2026-06-17 20:34:07.752757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b6bd8480abd'
down_revision = '5119a43fc059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_user_works',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for staff user work assignment'),
    sa.Column('staff_user_id', sa.Integer(), nullable=False, comment='Staff user ID'),
    sa.Column('work_id', sa.Integer(), nullable=False, comment='Work ID from EPIC.track'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Work role: TEAM_LEAD or TEAM_MEMBER'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this assignment is currently active'),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['track_works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_user_id', 'work_id', name='uq_staff_user_work')
    )
    with op.batch_alter_table('staff_user_works', schema=None) as batch_op:
        batch_op.create_index('idx_staff_user_works_staff_user_id', ['staff_user_id'], unique=False)
        batch_op.create_index('idx_staff_user_works_work_id', ['work_id'], unique=False)

    with op.batch_alter_table('account_project_non_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_project_non_works_account_project_id'))

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('project_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('project_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)

    with op.batch_alter_table('account_project_non_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_account_project_non_works_account_project_id'), ['account_project_id'], unique=False)

    with op.batch_alter_table('staff_user_works', schema=None) as batch_op:
        batch_op.drop_index('idx_staff_user_works_work_id')
        batch_op.drop_index('idx_staff_user_works_staff_user_id')

    op.drop_table('staff_user_works')
    # ### end Alembic commands ###
