"""Drop auth_guid from account_users

Revision ID: 8e3b41ce9e50
Revises: cba5ebbb4a74
Create Date: 2024-10-30 16:06:23.630182

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '8e3b41ce9e50'
down_revision = 'cba5ebbb4a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_users', 'auth_guid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_users', sa.Column('auth_guid', sa.String(), nullable=True))
    op.execute("UPDATE account_users au SET auth_guid = u.auth_guid FROM users u WHERE u.id = au.user_id")
    op.create_unique_constraint('unique_account_users_auth_guid', 'account_users', ['auth_guid'])
    op.alter_column('account_users', 'auth_guid', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###
