""" Add REVIEW_REJECTED to packagestatus and itemstatus

Revision ID: 910c8029a678
Revises: f7b107cb452d
Create Date: 2024-12-27 11:06:08.125708

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '910c8029a678'
down_revision = 'f7b107cb452d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$ 
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type typ 
                       JOIN pg_enum en ON en.enumtypid = typ.oid 
                       WHERE typ.typname = 'packagestatus' AND en.enumlabel = 'REVIEW_REJECTED') THEN
            ALTER TYPE packagestatus ADD VALUE 'REVIEW_REJECTED';
        END IF;
    END$$;
    """)

    op.execute("""
    DO $$ 
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type typ 
                       JOIN pg_enum en ON en.enumtypid = typ.oid 
                       WHERE typ.typname = 'itemstatus' AND en.enumlabel = 'REVIEW_REJECTED') THEN
            ALTER TYPE itemstatus ADD VALUE 'REVIEW_REJECTED';
        END IF;
    END$$;
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
