"""setup_revision_requested

Revision ID: 91623c6b08ca
Revises: 826fa830606a
Create Date: 2025-05-12 16:24:05.694744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91623c6b08ca'
down_revision = '826fa830606a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE noncanonicalpackagestatus ADD VALUE 'REVISION_REQUESTED';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
