"""note field in update request

Revision ID: 9232989dd92d
Revises: ea8e60c56cdd
Create Date: 2026-04-23 18:42:42.962346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9232989dd92d'
down_revision = 'ea8e60c56cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_updated_by', sa.String(), nullable=True, comment='Proponent user who last updated the note'))
        batch_op.add_column(sa.Column('note_updated_at', sa.DateTime(), nullable=True, comment='Timestamp when the note was last updated'))
        batch_op.alter_column('submission_item_types',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment='Array of submission item type IDs',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::integer[]"))
        batch_op.create_foreign_key('update_requests_note_updated_by_fkey', 'users', ['note_updated_by'], ['auth_guid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.drop_constraint('update_requests_note_updated_by_fkey', type_='foreignkey')
        batch_op.alter_column('submission_item_types',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment=None,
               existing_comment='Array of submission item type IDs',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::integer[]"))
        batch_op.drop_column('note_updated_at')
        batch_op.drop_column('note_updated_by')

    # ### end Alembic commands ###
