"""empty message

Revision ID: 94f284cada88
Revises: 1056f5daad12
Create Date: 2025-01-17 14:44:01.352047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94f284cada88'
down_revision = '1056f5daad12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_versions', schema=None) as batch_op:
        batch_op.drop_constraint('package_versions_original_package_id_fkey', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_versions', schema=None) as batch_op:
        batch_op.create_foreign_key('package_versions_original_package_id_fkey', 'packages', ['original_package_id'], ['id'])
    # ### end Alembic commands ###
