""" Add APPROVED to itemstatus

Revision ID: 95d97469c50e
Revises: 7be2617a23a4
Create Date: 2025-01-22 12:14:17.460348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95d97469c50e'
down_revision = '7be2617a23a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE itemstatus ADD VALUE IF NOT EXISTS 'APPROVED';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE itemstatus DROP VALUE IF EXISTS 'APPROVED';")
    # ### end Alembic commands ###