"""is_updated flag for item


Revision ID: 97cc1dfd50f4
Revises: d963598dd448
Create Date: 2026-05-25 14:10:17.484295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cc1dfd50f4'
down_revision = 'd963598dd448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_updated', sa.Boolean(), nullable=False, server_default='false', comment='Whether the item has been updated'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('is_updated')

    # ### end Alembic commands ###
