""" Add major_version, minor_version, and active columns to submissions

Revision ID: 9ac2e307816f
Revises: d01edacafbe7
Create Date: 2024-12-12 15:42:19.921590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac2e307816f'
down_revision = 'd01edacafbe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('minor_version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.drop_column('version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('active')
        batch_op.drop_column('minor_version')
        batch_op.drop_column('major_version')
    # ### end Alembic commands ###
