"""is_updated flag on submission

Revision ID: 9fc6de9887c3
Revises: 97cc1dfd50f4
Create Date: 2026-05-26 13:16:50.383196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc6de9887c3'
down_revision = '97cc1dfd50f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('is_updated')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_updated', sa.Boolean(), nullable=False, server_default='false', comment='Whether the submission has been updated'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('is_updated')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_updated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Whether the item has been updated'))

    # ### end Alembic commands ###
