"""

Revision ID: a6aa74a8e7c4
Revises: e9463a63a3e0
Create Date: 2025-01-13 13:49:10.250964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6aa74a8e7c4'
down_revision = 'e9463a63a3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epic_guid', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('epic_guid')
    # ### end Alembic commands ###
