""" Add cascade delete to several foreign key constraints

Revision ID: b8fe266573cc
Revises: 4b571b0106cc
Create Date: 2025-12-26 14:34:22.216071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8fe266573cc'
down_revision = '4b571b0106cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # account_projects.account_id → accounts.id
    op.drop_constraint('account_projects_account_id_fkey', 'account_projects', type_='foreignkey')
    op.create_foreign_key('account_projects_account_id_fkey', 'account_projects', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')

    # account_users.account_id → accounts.id
    op.drop_constraint('account_users_account_id_fkey', 'account_users', type_='foreignkey')
    op.create_foreign_key('account_users_account_id_fkey', 'account_users', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')

    # invitations.account_id → accounts.id
    op.drop_constraint('invitations_account_id_fkey', 'invitations', type_='foreignkey')
    op.create_foreign_key('invitations_account_id_fkey', 'invitations', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')

    # submission_review_entries.review_id → submission_reviews.id
    op.drop_constraint('submission_review_entries_review_id_fkey', 'submission_review_entries', type_='foreignkey')
    op.create_foreign_key('submission_review_entries_review_id_fkey', 'submission_review_entries', 'submission_reviews', ['review_id'], ['id'], ondelete='CASCADE')

    # submissions.item_id → items.id
    op.drop_constraint('submissions_item_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_item_id_fkey', 'submissions', 'items', ['item_id'], ['id'], ondelete='CASCADE')

    # user_roles.account_user_id → account_users.id
    op.drop_constraint('user_roles_account_user_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_account_user_id_fkey', 'user_roles', 'account_users', ['account_user_id'], ['id'], ondelete='CASCADE')

    # user_roles.account_project_id → account_projects.id
    op.drop_constraint('user_roles_account_project_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_account_project_id_fkey', 'user_roles', 'account_projects', ['account_project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse all changes - remove CASCADE from constraints
    op.drop_constraint('user_roles_account_project_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_account_project_id_fkey', 'user_roles', 'account_projects', ['account_project_id'], ['id'])

    op.drop_constraint('user_roles_account_user_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_account_user_id_fkey', 'user_roles', 'account_users', ['account_user_id'], ['id'])

    op.drop_constraint('submissions_item_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_item_id_fkey', 'submissions', 'items', ['item_id'], ['id'])

    op.drop_constraint('submission_review_entries_review_id_fkey', 'submission_review_entries', type_='foreignkey')
    op.create_foreign_key('submission_review_entries_review_id_fkey', 'submission_review_entries', 'submission_reviews', ['review_id'], ['id'])

    op.drop_constraint('invitations_account_id_fkey', 'invitations', type_='foreignkey')
    op.create_foreign_key('invitations_account_id_fkey', 'invitations', 'accounts', ['account_id'], ['id'])

    op.drop_constraint('account_users_account_id_fkey', 'account_users', type_='foreignkey')
    op.create_foreign_key('account_users_account_id_fkey', 'account_users', 'accounts', ['account_id'], ['id'])

    op.drop_constraint('account_projects_account_id_fkey', 'account_projects', type_='foreignkey')
    op.create_foreign_key('account_projects_account_id_fkey', 'account_projects', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###
