"""

Revision ID: bd17a1010bad
Revises: e635c4f73779
Create Date: 2025-06-09 11:58:10.899194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd17a1010bad'
down_revision = 'e635c4f73779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_staff_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('internal_staff_documents_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'packages', ['package_id'], ['id'])
        batch_op.drop_column('item_id')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('project_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('items_package_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'packages', ['package_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_staff_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('internal_staff_documents_item_id_fkey', 'items', ['item_id'], ['id'])
        batch_op.drop_column('package_id')
    # ### end Alembic commands ###
