""" Add package_versions table and active column to packages

Revision ID: be096790789f
Revises: 640535864292
Create Date: 2024-12-11 15:12:19.101988

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'be096790789f'
down_revision = '640535864292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('original_package_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', 'original_package_id')
    )
    with op.batch_alter_table('package_versions', schema=None) as batch_op:
        batch_op.create_index('idx_package_versions_original_package_id', ['original_package_id'], unique=False)
        batch_op.create_index('idx_package_versions_package_id', ['package_id'], unique=False)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('package_versions', schema=None) as batch_op:
        batch_op.drop_index('idx_package_versions_package_id')
        batch_op.drop_index('idx_package_versions_original_package_id')

    op.drop_table('package_versions')
    # ### end Alembic commands ###
