"""role mapping

Revision ID: c36f4c0117b8
Revises: 357e22a9cf8f
Create Date: 2025-03-03 16:07:49.634481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c36f4c0117b8'
down_revision = '357e22a9cf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_user_id', sa.Integer(), nullable=False),
    sa.Column('account_project_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['account_project_id'], ['account_projects.id'], ),
    sa.ForeignKeyConstraint(['account_user_id'], ['account_users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('account_user_roles')
    op.drop_table('account_roles')

    # Insert predefined roles using sa.text()
    conn = op.get_bind()
    conn.execute(sa.text("""
        INSERT INTO roles (role_name, label, description, created_date) VALUES 
        ('ACCOUNT_PRIMARY_ADMIN', 'Account Administrator', 'Full access to an account', NOW()),
        ('PROJECT_ADMIN', 'Project Administrator', 'Full access to a project', NOW()),
        ('SUBMISSION_ADMIN', 'Contributor - All Submissions', 'Can manage all submissions within a project', NOW()),
        ('SPECIFIC_SUBMISSION_CONTRIBUTOR', 'Contributor - Specific Submissions', 'Can manage only assigned submissions', NOW());
    """))

    # Migrate existing roles: Set all to "ACCOUNT_PRIMARY_ADMIN"
    conn.execute(sa.text("""
            UPDATE user_roles 
            SET role_id = (SELECT id FROM roles WHERE role_name = 'ACCOUNT_PRIMARY_ADMIN')
        """))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('account_roles',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('role_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
                    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='roles_pkey')
                    )

    op.create_table('account_user_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_user_id'], ['account_users.id'], name='account_roles_account_user_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['account_roles.id'], name='account_roles_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='account_roles_pkey')
    )

    op.drop_table('user_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
