"""create_proponents_table

Revision ID: c7d8e9f0a1b2
Revises: b8fe266573cc
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c7d8e9f0a1b2'
down_revision = 'b8fe266573cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("DO $$ BEGIN CREATE TYPE proponentstatus AS ENUM ('ELIGIBLE', 'INELIGIBLE', 'PENDING_ONBOARDING', 'ONBOARDED'); EXCEPTION WHEN duplicate_object THEN null; END $$;"))
    
    # Use postgresql.ENUM with create_type=False to prevent SQLAlchemy from trying to create it again
    proponent_status_enum = postgresql.ENUM('ELIGIBLE', 'INELIGIBLE', 'PENDING_ONBOARDING', 'ONBOARDED', name='proponentstatus', create_type=False)
    
    op.create_table('proponents',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', proponent_status_enum, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Insert distinct proponents from projects table
    # Use proponent_id from projects as id in proponents table
    # If multiple projects have the same proponent_id, use the first proponent_name
    conn.execute(sa.text("""
        INSERT INTO proponents (id, name, status, is_deleted)
        SELECT DISTINCT ON (proponent_id)
            proponent_id as id,
            proponent_name as name,
            NULL as status,
            false as is_deleted
        FROM projects
        WHERE proponent_id IS NOT NULL
        ORDER BY proponent_id, id
        ON CONFLICT (id) DO NOTHING
    """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proponents')
    
    # Drop the enum type
    proponent_status_enum = sa.Enum('ELIGIBLE', 'INELIGIBLE', 'PENDING_ONBOARDING', 'ONBOARDED', name='proponentstatus')
    proponent_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

