"""create_proponents_table

Revision ID: c7d8e9f0a1b2
Revises: b8fe266573cc
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c7d8e9f0a1b2'
down_revision = 'b8fe266573cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type if it doesn't exist (using PostgreSQL-specific syntax)
    conn = op.get_bind()
    conn.execute(sa.text("DO $$ BEGIN CREATE TYPE proponentstatus AS ENUM ('Eligible', 'Ineligible', 'Pending Onboarding', 'Onboarded'); EXCEPTION WHEN duplicate_object THEN null; END $$;"))
    
    # Use postgresql.ENUM with create_type=False to prevent SQLAlchemy from trying to create it again
    proponent_status_enum = postgresql.ENUM('Eligible', 'Ineligible', 'Pending Onboarding', 'Onboarded', name='proponentstatus', create_type=False)
    
    op.create_table('proponents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proponent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', proponent_status_enum, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proponent_id')
    )
    op.create_index('ix_proponents_proponent_id', 'proponents', ['proponent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proponents_proponent_id', table_name='proponents')
    op.drop_table('proponents')
    
    # Drop the enum type
    proponent_status_enum = sa.Enum('Eligible', 'Ineligible', 'Pending Onboarding', 'Onboarded', name='proponentstatus')
    proponent_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

