"""add_foreign_keys_projects_and_accounts_proponent_id_to_proponents

Revision ID: d1e2f3a4b5c6
Revises: c7d8e9f0a1b2
Create Date: 2025-01-27 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e2f3a4b5c6'
down_revision = 'c7d8e9f0a1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_projects_proponent_id_proponents',
            'proponents',
            ['proponent_id'],
            ['id']
        )
    
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_accounts_proponent_id_proponents',
            'proponents',
            ['proponent_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accounts_proponent_id_proponents', type_='foreignkey')
    
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_proponent_id_proponents', type_='foreignkey')
    # ### end Alembic commands ###
