"""add_foreign_key_accounts_proponent_id_to_proponents

Revision ID: d2e3f4a5b6c7
Revises: d1e2f3a4b5c6
Create Date: 2025-01-27 11:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e3f4a5b6c7'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_accounts_proponent_id_proponents',
            'proponents',
            ['proponent_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accounts_proponent_id_proponents', type_='foreignkey')
    # ### end Alembic commands ###
