"""add_title_and_unique_constraint_to_package_types

Revision ID: d4ea378228e4
Revises: db8937ea18af
Create Date: 2026-04-08 22:21:47.688586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ea378228e4'
down_revision = 'db8937ea18af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True, comment='Display title for the package type'))
        batch_op.create_unique_constraint('uq_package_type_name_phase', ['name', 'phase_id'])

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True, comment='Description of the package'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('package_types', schema=None) as batch_op:
        batch_op.drop_constraint('uq_package_type_name_phase', type_='unique')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
