""" Add note column to update_requests

Revision ID: d9bd8b91c56b
Revises: da84ae0195fe
Create Date: 2025-01-02 16:03:20.200816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bd8b91c56b'
down_revision = 'da84ae0195fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.drop_column('note')
    # ### end Alembic commands ###
