""" Rename note column to reason in update_requests table

Revision ID: da84ae0195fe
Revises: 6ad5f5d3dcb1
Create Date: 2025-01-02 15:37:23.708345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da84ae0195fe'
down_revision = '6ad5f5d3dcb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.alter_column('note', new_column_name='reason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.alter_column('reason', new_column_name='note')
    # ### end Alembic commands ###
