"""

Revision ID: db5c2351e6c1
Revises: 3eab559030cf
Create Date: 2025-04-15 14:59:40.406676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db5c2351e6c1'
down_revision = '3eab559030cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE packagestatus ADD VALUE IF NOT EXISTS 'REVISION_REQUIRED'")
    op.execute("ALTER TYPE packagestatus ADD VALUE IF NOT EXISTS 'NO_REVISION_REQUIRED'")
    op.execute("ALTER TYPE packagestatus ADD VALUE IF NOT EXISTS 'RESUBMITTED'")
    op.execute("ALTER TYPE packagestatus ADD VALUE IF NOT EXISTS 'CREATED'") 
    op.execute("ALTER TYPE packagestatus ADD VALUE IF NOT EXISTS 'FAILED_CONSULTATION_CHECK'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
