""" add internal_staff_documents table

Revision ID: df9c90534e9d
Revises: 5bf7b1f9a81c
Create Date: 2024-11-08 14:09:53.880062

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'df9c90534e9d'
down_revision = '5bf7b1f9a81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_staff_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('S3', 'LINK', name='internalstaffdocumenttype'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internal_staff_documents')
    # ### end Alembic commands ###
