"""add_user_status

Revision ID: dfd81c02e843
Revises: 8e273ea9fe24
Create Date: 2025-04-29 12:54:37.170409

"""
from alembic import op
from datetime import datetime
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfd81c02e843'
down_revision = '8e273ea9fe24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    user_status = sa.table('user_status',
                           sa.column('id', sa.Integer),
                           sa.column('status_name', sa.String),
                           sa.column('description', sa.String),
                           sa.column('created_date', sa.DateTime),
                           sa.column('updated_date', sa.DateTime))

    op.bulk_insert(user_status, [
        {'id': 1, 'status_name': 'ACTIVE', 'description': 'Active User', 'created_date': datetime.utcnow(),
         'updated_date': datetime.utcnow()},
        {'id': 2, 'status_name': 'INACTIVE', 'description': 'Inactive User', 'created_date': datetime.utcnow(),
         'updated_date': datetime.utcnow()}
    ])

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('TRUE'))
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('status_id', sa.Integer(), nullable=False, server_default='1')
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status_id', server_default=None)

    # Create foreign key with a fixed name
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_status_id', 'user_status', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_status_id', type_='foreignkey')
        batch_op.drop_column('status_id')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_column('active')

    op.drop_table('user_status')
    # ### end Alembic commands ###
