"""add activity_log note

Revision ID: e6c5b195f6aa
Revises: f2a7c1d9e4b3
Create Date: 2026-10-09 15:20:24.764554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c5b195f6aa'
down_revision = 'f2a7c1d9e4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('decision_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('decision_date')
    # ### end Alembic commands ###
