"""success_message field added in package_Type 


Revision ID: e8e42981ee80
Revises: 9fc6de9887c3
Create Date: 2026-06-01 11:06:46.839097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e42981ee80'
down_revision = '9fc6de9887c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('success_message', sa.String(length=255), nullable=True, comment='Success message to display to user after submission'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_types', schema=None) as batch_op:
        batch_op.drop_column('success_message')

    # ### end Alembic commands ###
