""" Add status column to submissions

Revision ID: e9463a63a3e0
Revises: d9bd8b91c56b
Create Date: 2025-01-08 15:01:28.799671

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e9463a63a3e0'
down_revision = 'd9bd8b91c56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    submission_status = sa.Enum('SUBMITTED', 'REJECTED', 'APPROVED', 'PENDING', name='submissionstatus')
    submission_status.create(op.get_bind())
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', submission_status, nullable=True, default='PENDING'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('status')
    submission_status = sa.Enum('SUBMITTED', 'REJECTED', 'APPROVED', 'PENDING', name='submissionstatus')
    submission_status.drop(op.get_bind())
    # ### end Alembic commands ###
