"""Add BaseModel to Proponent

Revision ID: e9ede8ab9185
Revises: 8e4d626a3a26
Create Date: 2026-01-19 11:53:43.188596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9ede8ab9185'
down_revision = '8e4d626a3a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proponents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proponents', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
