"""update mp name

Revision ID: ed2a308d1368
Revises: c5f4cd047da4
Create Date: 2025-07-03 11:39:33.813176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed2a308d1368'
down_revision = 'c5f4cd047da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update all packages to have condition number and name in the format
    op.execute(
        """
        UPDATE packages p
        SET name = CONCAT(
            pm.json->'main_condition'->>'condition_number', 
            ' - ', 
            pm.json->'main_condition'->>'condition_name'
        )
        FROM package_metadata pm
        WHERE p.id = pm.package_id 
        AND pm.json->'main_condition'->>'condition_number' IS NOT NULL
        AND pm.json->'main_condition'->>'condition_name' IS NOT NULL
        """
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: We cannot easily revert this as we don't know what the original names were
    # This is a data migration that changes existing data format
    pass
    # ### end Alembic commands ###
