"""adding display_name for phase name

Revision ID: f1d8ab8c2d30
Revises: e27054af162b
Create Date: 2026-02-26 15:12:55.957537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d8ab8c2d30'
down_revision = 'e27054af162b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop unnecessary indexes from small tables
    with op.batch_alter_table('package_types', schema=None) as batch_op:
        batch_op.drop_index('idx_package_types_name')
        batch_op.drop_index('idx_package_types_phase_id')

    # Drop old index and create optimized indexes for packages table
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index('idx_packages_account_project_work_id')
    
    # Create new indexes for packages
    op.create_index('idx_packages_account_project_id', 'packages', ['account_project_id'])
    op.create_index(
        'idx_packages_account_project_work_id', 
        'packages', 
        ['account_project_work_id'],
        postgresql_where=sa.text('account_project_work_id IS NOT NULL')
    )

    # Add display_name and ea_act_name columns to track_phases
    with op.batch_alter_table('track_phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=255), nullable=True, comment='Submit-specific phase name override; defaults to name field if not set'))
        batch_op.add_column(sa.Column('ea_act_name', sa.String(length=255), nullable=True, comment='Environmental Assessment Act name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop display_name and ea_act_name columns from track_phases
    with op.batch_alter_table('track_phases', schema=None) as batch_op:
        batch_op.drop_column('ea_act_name')
        batch_op.drop_column('display_name')

    # Drop new optimized indexes
    op.drop_index('idx_packages_account_project_work_id', table_name='packages')
    op.drop_index('idx_packages_account_project_id', table_name='packages')

    # Restore old indexes
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index('idx_packages_account_project_work_id', ['account_project_work_id'], unique=False)

    with op.batch_alter_table('package_types', schema=None) as batch_op:
        batch_op.create_index('idx_package_types_phase_id', ['phase_id'], unique=False)
        batch_op.create_index('idx_package_types_name', ['name'], unique=False)

    # ### end Alembic commands ###
