"""add unique constraint on projects(name, proponent_id)

Revision ID: f3e5506ce9df
Revises: 1839037128e2
Create Date: 2025-09-18 13:57:22.999202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3e5506ce9df'
down_revision = '1839037128e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_projects_name_proponent', ['name', 'proponent_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_projects_name_proponent', type_='unique')

    # ### end Alembic commands ###
