""" Add status column to update_requests table

Revision ID: f48c2afae65f
Revises: e9463a63a3e0
Create Date: 2025-01-10 17:39:17.441141

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f48c2afae65f'
down_revision = 'e9463a63a3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type
    op.execute("CREATE TYPE updaterequeststatus AS ENUM ('OPEN', 'PENDING_REVIEW', 'CLOSED')")

    # Add the column with a default value
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('OPEN', 'PENDING_REVIEW', 'CLOSED',
                                                        name='updaterequeststatus'), nullable=False,
                                      server_default='OPEN'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_requests', schema=None) as batch_op:
        batch_op.drop_column('status')
    # Drop the enum type
    op.execute("DROP TYPE updaterequeststatus")
    # ### end Alembic commands ###
