""" Add unique constraint to items table

Revision ID: f7b107cb452d
Revises: 198ebece2242
Create Date: 2024-12-24 16:18:48.067852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b107cb452d'
down_revision = '198ebece2242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_items_package_id_type_id', ['package_id', 'type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_items_package_id_type_id', type_='unique')
    # ### end Alembic commands ###
