""" Add update_requests table

Revision ID: f9abaf338ea0
Revises: 9ac2e307816f
Create Date: 2024-12-13 15:49:55.921058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9abaf338ea0'
down_revision = '9ac2e307816f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_package_id', sa.Integer(), nullable=False),
    sa.Column('submission_item_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.auth_guid'], ),
    sa.ForeignKeyConstraint(['submission_package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_requests')
    # ### end Alembic commands ###
