"""add_accepted_status_to_updaterequeststatus

Revision ID: f9cdde365d29
Revises: 2a8e579da45c
Create Date: 2025-02-19 16:58:23.507357

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f9cdde365d29'
down_revision = '2a8e579da45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE updaterequeststatus ADD VALUE 'ACCEPTED'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
