"""Added activity log table

Revision ID: fbc21a66ad64
Revises: 7be2617a23a4
Create Date: 2025-02-03 16:13:39.057004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbc21a66ad64'
down_revision = '7be2617a23a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('activity_at', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_entity_version'), ['entity_version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ##

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_entity_version'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_entity_id'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
