"""role added to invite 

Revision ID: fcf3e7869c66
Revises: c36f4c0117b8
Create Date: 2025-03-04 17:30:01.954590

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fcf3e7869c66'
down_revision = 'c36f4c0117b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_invite_role_id', 'roles', ['role_id'], ['id'])
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_invite_package_id', 'packages', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invite_role_id', type_='foreignkey')
        batch_op.drop_column('role_id')
        batch_op.drop_constraint('fk_invite_package_id', type_='foreignkey')
        batch_op.drop_column('package_id')

        # ### end Alembic commands ###
