"""made package_ids in invite

Revision ID: fe3d9df59f7a
Revises: fcf3e7869c66
Create Date: 2025-03-06 10:27:28.199454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe3d9df59f7a'
down_revision = 'fcf3e7869c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_ids', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.drop_column('project_ids')
        batch_op.add_column(sa.Column('project_ids', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.drop_constraint('fk_invite_package_id', type_='foreignkey')
        batch_op.drop_column('package_id')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_ids', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.drop_constraint('user_roles_package_id_fkey', type_='foreignkey')
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_roles_package_id_fkey', 'packages', ['package_id'], ['id'])
        batch_op.drop_column('package_ids')


    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_column('package_ids')
        batch_op.add_column(sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('project_ids')
        batch_op.add_column(sa.Column('project_ids', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_invite_package_id', 'packages', ['package_id'], ['id'])

    # ### end Alembic commands ###
