/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as ErrorImport } from './routes/error'
import { Route as IndexImport } from './routes/index'
import { Route as OidcCallbackIndexImport } from './routes/oidc-callback/index'
import { Route as StaffStaffLayoutImport } from './routes/staff/_staffLayout'
import { Route as ProponentProponentLayoutImport } from './routes/proponent/_proponentLayout'
import { Route as ProponentRegistrationIndexImport } from './routes/proponent/registration/index'
import { Route as ProponentRegistrationCreateAccountImport } from './routes/proponent/registration/create-account'
import { Route as ProponentRegistrationCompleteImport } from './routes/proponent/registration/complete'
import { Route as ProponentProponentLayoutProfileImport } from './routes/proponent/_proponentLayout/profile'
import { Route as StaffStaffLayoutProjectsIndexImport } from './routes/staff/_staffLayout/projects/index'
import { Route as ProponentProponentLayoutProjectsIndexImport } from './routes/proponent/_proponentLayout/projects/index'
import { Route as StaffStaffLayoutProjectsAllProjectsLayoutImport } from './routes/staff/_staffLayout/projects/_allProjectsLayout'
import { Route as ProponentProponentLayoutProjectsAllProjectsLayoutImport } from './routes/proponent/_proponentLayout/projects/_allProjectsLayout'
import { Route as StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutImport } from './routes/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout'
import { Route as ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutImport } from './routes/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout'
import { Route as StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutIndexImport } from './routes/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/index'
import { Route as ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutIndexImport } from './routes/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/index'
import { Route as ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutNewSubmissionImport } from './routes/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/new-submission'
import { Route as StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport } from './routes/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
import { Route as ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport } from './routes/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
import { Route as StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport } from './routes/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index'
import { Route as ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport } from './routes/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index'
import { Route as StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport } from './routes/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
import { Route as ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport } from './routes/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'

// Create Virtual Routes

const StaffImport = createFileRoute('/staff')()
const ProponentImport = createFileRoute('/proponent')()
const StaffStaffLayoutProjectsImport = createFileRoute(
  '/staff/_staffLayout/projects',
)()
const ProponentProponentLayoutProjectsImport = createFileRoute(
  '/proponent/_proponentLayout/projects',
)()
const ProponentProponentLayoutAboutpageLazyImport = createFileRoute(
  '/proponent/_proponentLayout/aboutpage',
)()
const StaffStaffLayoutProjectsAllProjectsLayoutProjectIdImport =
  createFileRoute(
    '/staff/_staffLayout/projects/_allProjectsLayout/$projectId',
  )()
const ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdImport =
  createFileRoute(
    '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId',
  )()
const StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport =
  createFileRoute(
    '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId',
  )()
const ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport =
  createFileRoute(
    '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId',
  )()

// Create/Update Routes

const StaffRoute = StaffImport.update({
  path: '/staff',
  getParentRoute: () => rootRoute,
} as any)

const ProponentRoute = ProponentImport.update({
  path: '/proponent',
  getParentRoute: () => rootRoute,
} as any)

const NotFoundRoute = NotFoundImport.update({
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OidcCallbackIndexRoute = OidcCallbackIndexImport.update({
  path: '/oidc-callback/',
  getParentRoute: () => rootRoute,
} as any)

const StaffStaffLayoutRoute = StaffStaffLayoutImport.update({
  id: '/_staffLayout',
  getParentRoute: () => StaffRoute,
} as any)

const ProponentProponentLayoutRoute = ProponentProponentLayoutImport.update({
  id: '/_proponentLayout',
  getParentRoute: () => ProponentRoute,
} as any)

const StaffStaffLayoutProjectsRoute = StaffStaffLayoutProjectsImport.update({
  path: '/projects',
  getParentRoute: () => StaffStaffLayoutRoute,
} as any)

const ProponentProponentLayoutProjectsRoute =
  ProponentProponentLayoutProjectsImport.update({
    path: '/projects',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const ProponentRegistrationIndexRoute = ProponentRegistrationIndexImport.update(
  {
    path: '/registration/',
    getParentRoute: () => ProponentRoute,
  } as any,
)

const ProponentProponentLayoutAboutpageLazyRoute =
  ProponentProponentLayoutAboutpageLazyImport.update({
    path: '/aboutpage',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any).lazy(() =>
    import('./routes/proponent/_proponentLayout/aboutpage.lazy').then(
      (d) => d.Route,
    ),
  )

const ProponentRegistrationCreateAccountRoute =
  ProponentRegistrationCreateAccountImport.update({
    path: '/registration/create-account',
    getParentRoute: () => ProponentRoute,
  } as any)

const ProponentRegistrationCompleteRoute =
  ProponentRegistrationCompleteImport.update({
    path: '/registration/complete',
    getParentRoute: () => ProponentRoute,
  } as any)

const ProponentProponentLayoutProfileRoute =
  ProponentProponentLayoutProfileImport.update({
    path: '/profile',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const StaffStaffLayoutProjectsIndexRoute =
  StaffStaffLayoutProjectsIndexImport.update({
    path: '/',
    getParentRoute: () => StaffStaffLayoutProjectsRoute,
  } as any)

const ProponentProponentLayoutProjectsIndexRoute =
  ProponentProponentLayoutProjectsIndexImport.update({
    path: '/',
    getParentRoute: () => ProponentProponentLayoutProjectsRoute,
  } as any)

const StaffStaffLayoutProjectsAllProjectsLayoutRoute =
  StaffStaffLayoutProjectsAllProjectsLayoutImport.update({
    id: '/_allProjectsLayout',
    getParentRoute: () => StaffStaffLayoutProjectsRoute,
  } as any)

const ProponentProponentLayoutProjectsAllProjectsLayoutRoute =
  ProponentProponentLayoutProjectsAllProjectsLayoutImport.update({
    id: '/_allProjectsLayout',
    getParentRoute: () => ProponentProponentLayoutProjectsRoute,
  } as any)

const StaffStaffLayoutProjectsAllProjectsLayoutProjectIdRoute =
  StaffStaffLayoutProjectsAllProjectsLayoutProjectIdImport.update({
    path: '/$projectId',
    getParentRoute: () => StaffStaffLayoutProjectsAllProjectsLayoutRoute,
  } as any)

const ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdRoute =
  ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdImport.update({
    path: '/$projectId',
    getParentRoute: () =>
      ProponentProponentLayoutProjectsAllProjectsLayoutRoute,
  } as any)

const StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutRoute =
  StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutImport.update({
    id: '/_projectLayout',
    getParentRoute: () =>
      StaffStaffLayoutProjectsAllProjectsLayoutProjectIdRoute,
  } as any)

const ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutRoute =
  ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutImport.update(
    {
      id: '/_projectLayout',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdRoute,
    } as any,
  )

const StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutIndexRoute =
  StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutIndexImport.update(
    {
      path: '/',
      getParentRoute: () =>
        StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutIndexRoute =
  ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutIndexImport.update(
    {
      path: '/',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutNewSubmissionRoute =
  ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutNewSubmissionImport.update(
    {
      path: '/new-submission',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutRoute,
    } as any,
  )

const StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute =
  StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport.update(
    {
      path: '/submission-packages/$submissionPackageId',
      getParentRoute: () =>
        StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute =
  ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport.update(
    {
      path: '/submission-packages/$submissionPackageId',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutRoute,
    } as any,
  )

const StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute =
  StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport.update(
    {
      id: '/_submissionLayout',
      getParentRoute: () =>
        StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute,
    } as any,
  )

const ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute =
  ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport.update(
    {
      id: '/_submissionLayout',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute,
    } as any,
  )

const StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute =
  StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport.update(
    {
      path: '/',
      getParentRoute: () =>
        StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute =
  ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport.update(
    {
      path: '/',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

const StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute =
  StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport.update(
    {
      path: '/submissions/$submissionId',
      getParentRoute: () =>
        StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute =
  ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport.update(
    {
      path: '/submissions/$submissionId',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/proponent': {
      id: '/proponent'
      path: '/proponent'
      fullPath: '/proponent'
      preLoaderRoute: typeof ProponentImport
      parentRoute: typeof rootRoute
    }
    '/proponent/_proponentLayout': {
      id: '/proponent/_proponentLayout'
      path: '/proponent'
      fullPath: '/proponent'
      preLoaderRoute: typeof ProponentProponentLayoutImport
      parentRoute: typeof ProponentRoute
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffImport
      parentRoute: typeof rootRoute
    }
    '/staff/_staffLayout': {
      id: '/staff/_staffLayout'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffStaffLayoutImport
      parentRoute: typeof StaffRoute
    }
    '/oidc-callback/': {
      id: '/oidc-callback/'
      path: '/oidc-callback'
      fullPath: '/oidc-callback'
      preLoaderRoute: typeof OidcCallbackIndexImport
      parentRoute: typeof rootRoute
    }
    '/proponent/_proponentLayout/profile': {
      id: '/proponent/_proponentLayout/profile'
      path: '/profile'
      fullPath: '/proponent/profile'
      preLoaderRoute: typeof ProponentProponentLayoutProfileImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/registration/complete': {
      id: '/proponent/registration/complete'
      path: '/registration/complete'
      fullPath: '/proponent/registration/complete'
      preLoaderRoute: typeof ProponentRegistrationCompleteImport
      parentRoute: typeof ProponentImport
    }
    '/proponent/registration/create-account': {
      id: '/proponent/registration/create-account'
      path: '/registration/create-account'
      fullPath: '/proponent/registration/create-account'
      preLoaderRoute: typeof ProponentRegistrationCreateAccountImport
      parentRoute: typeof ProponentImport
    }
    '/proponent/_proponentLayout/aboutpage': {
      id: '/proponent/_proponentLayout/aboutpage'
      path: '/aboutpage'
      fullPath: '/proponent/aboutpage'
      preLoaderRoute: typeof ProponentProponentLayoutAboutpageLazyImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/registration/': {
      id: '/proponent/registration/'
      path: '/registration'
      fullPath: '/proponent/registration'
      preLoaderRoute: typeof ProponentRegistrationIndexImport
      parentRoute: typeof ProponentImport
    }
    '/proponent/_proponentLayout/projects': {
      id: '/proponent/_proponentLayout/projects'
      path: '/projects'
      fullPath: '/proponent/projects'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/_proponentLayout/projects/_allProjectsLayout': {
      id: '/proponent/_proponentLayout/projects/_allProjectsLayout'
      path: '/projects'
      fullPath: '/proponent/projects'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutImport
      parentRoute: typeof ProponentProponentLayoutProjectsRoute
    }
    '/staff/_staffLayout/projects': {
      id: '/staff/_staffLayout/projects'
      path: '/projects'
      fullPath: '/staff/projects'
      preLoaderRoute: typeof StaffStaffLayoutProjectsImport
      parentRoute: typeof StaffStaffLayoutImport
    }
    '/staff/_staffLayout/projects/_allProjectsLayout': {
      id: '/staff/_staffLayout/projects/_allProjectsLayout'
      path: '/projects'
      fullPath: '/staff/projects'
      preLoaderRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutImport
      parentRoute: typeof StaffStaffLayoutProjectsRoute
    }
    '/proponent/_proponentLayout/projects/': {
      id: '/proponent/_proponentLayout/projects/'
      path: '/'
      fullPath: '/proponent/projects/'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsIndexImport
      parentRoute: typeof ProponentProponentLayoutProjectsImport
    }
    '/staff/_staffLayout/projects/': {
      id: '/staff/_staffLayout/projects/'
      path: '/'
      fullPath: '/staff/projects/'
      preLoaderRoute: typeof StaffStaffLayoutProjectsIndexImport
      parentRoute: typeof StaffStaffLayoutProjectsImport
    }
    '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId': {
      id: '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId'
      path: '/$projectId'
      fullPath: '/proponent/projects/$projectId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdImport
      parentRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutImport
    }
    '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout': {
      id: '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout'
      path: '/$projectId'
      fullPath: '/proponent/projects/$projectId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutImport
      parentRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdRoute
    }
    '/staff/_staffLayout/projects/_allProjectsLayout/$projectId': {
      id: '/staff/_staffLayout/projects/_allProjectsLayout/$projectId'
      path: '/$projectId'
      fullPath: '/staff/projects/$projectId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdImport
      parentRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutImport
    }
    '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout': {
      id: '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout'
      path: '/$projectId'
      fullPath: '/staff/projects/$projectId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutImport
      parentRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdRoute
    }
    '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/new-submission': {
      id: '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/new-submission'
      path: '/new-submission'
      fullPath: '/proponent/projects/$projectId/new-submission'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutNewSubmissionImport
      parentRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutImport
    }
    '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/': {
      id: '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/'
      path: '/'
      fullPath: '/proponent/projects/$projectId/'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutIndexImport
      parentRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutImport
    }
    '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/': {
      id: '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/'
      path: '/'
      fullPath: '/staff/projects/$projectId/'
      preLoaderRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutIndexImport
      parentRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutImport
    }
    '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId': {
      id: '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport
      parentRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutImport
    }
    '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': {
      id: '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
      parentRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute
    }
    '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId': {
      id: '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport
      parentRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutImport
    }
    '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': {
      id: '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
      parentRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute
    }
    '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': {
      id: '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
      path: '/'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId/'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport
      parentRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
    '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': {
      id: '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
      path: '/'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId/'
      preLoaderRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport
      parentRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
    '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': {
      id: '/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport
      parentRoute: typeof ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
    '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': {
      id: '/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport
      parentRoute: typeof StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ErrorRoute,
  NotFoundRoute,
  ProponentRoute: ProponentRoute.addChildren({
    ProponentProponentLayoutRoute: ProponentProponentLayoutRoute.addChildren({
      ProponentProponentLayoutProfileRoute,
      ProponentProponentLayoutAboutpageLazyRoute,
      ProponentProponentLayoutProjectsRoute:
        ProponentProponentLayoutProjectsRoute.addChildren({
          ProponentProponentLayoutProjectsAllProjectsLayoutRoute:
            ProponentProponentLayoutProjectsAllProjectsLayoutRoute.addChildren({
              ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdRoute:
                ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdRoute.addChildren(
                  {
                    ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutRoute:
                      ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutRoute.addChildren(
                        {
                          ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutNewSubmissionRoute,
                          ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutIndexRoute,
                          ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute:
                            ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute.addChildren(
                              {
                                ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute:
                                  ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute.addChildren(
                                    {
                                      ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute,
                                      ProponentProponentLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute,
                                    },
                                  ),
                              },
                            ),
                        },
                      ),
                  },
                ),
            }),
          ProponentProponentLayoutProjectsIndexRoute,
        }),
    }),
    ProponentRegistrationCompleteRoute,
    ProponentRegistrationCreateAccountRoute,
    ProponentRegistrationIndexRoute,
  }),
  StaffRoute: StaffRoute.addChildren({
    StaffStaffLayoutRoute: StaffStaffLayoutRoute.addChildren({
      StaffStaffLayoutProjectsRoute: StaffStaffLayoutProjectsRoute.addChildren({
        StaffStaffLayoutProjectsAllProjectsLayoutRoute:
          StaffStaffLayoutProjectsAllProjectsLayoutRoute.addChildren({
            StaffStaffLayoutProjectsAllProjectsLayoutProjectIdRoute:
              StaffStaffLayoutProjectsAllProjectsLayoutProjectIdRoute.addChildren(
                {
                  StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutRoute:
                    StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutRoute.addChildren(
                      {
                        StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutIndexRoute,
                        StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute:
                          StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute.addChildren(
                            {
                              StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute:
                                StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute.addChildren(
                                  {
                                    StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute,
                                    StaffStaffLayoutProjectsAllProjectsLayoutProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute,
                                  },
                                ),
                            },
                          ),
                      },
                    ),
                },
              ),
          }),
        StaffStaffLayoutProjectsIndexRoute,
      }),
    }),
  }),
  OidcCallbackIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/error",
        "/not-found",
        "/proponent",
        "/staff",
        "/oidc-callback/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/proponent": {
      "filePath": "proponent",
      "children": [
        "/proponent/_proponentLayout",
        "/proponent/registration/complete",
        "/proponent/registration/create-account",
        "/proponent/registration/"
      ]
    },
    "/proponent/_proponentLayout": {
      "filePath": "proponent/_proponentLayout.tsx",
      "parent": "/proponent",
      "children": [
        "/proponent/_proponentLayout/profile",
        "/proponent/_proponentLayout/aboutpage",
        "/proponent/_proponentLayout/projects"
      ]
    },
    "/staff": {
      "filePath": "staff",
      "children": [
        "/staff/_staffLayout"
      ]
    },
    "/staff/_staffLayout": {
      "filePath": "staff/_staffLayout.tsx",
      "parent": "/staff",
      "children": [
        "/staff/_staffLayout/projects"
      ]
    },
    "/oidc-callback/": {
      "filePath": "oidc-callback/index.tsx"
    },
    "/proponent/_proponentLayout/profile": {
      "filePath": "proponent/_proponentLayout/profile.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/proponent/registration/complete": {
      "filePath": "proponent/registration/complete.tsx",
      "parent": "/proponent"
    },
    "/proponent/registration/create-account": {
      "filePath": "proponent/registration/create-account.tsx",
      "parent": "/proponent"
    },
    "/proponent/_proponentLayout/aboutpage": {
      "filePath": "proponent/_proponentLayout/aboutpage.lazy.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/proponent/registration/": {
      "filePath": "proponent/registration/index.tsx",
      "parent": "/proponent"
    },
    "/proponent/_proponentLayout/projects": {
      "filePath": "proponent/_proponentLayout/projects",
      "parent": "/proponent/_proponentLayout",
      "children": [
        "/proponent/_proponentLayout/projects/_allProjectsLayout",
        "/proponent/_proponentLayout/projects/"
      ]
    },
    "/proponent/_proponentLayout/projects/_allProjectsLayout": {
      "filePath": "proponent/_proponentLayout/projects/_allProjectsLayout.tsx",
      "parent": "/proponent/_proponentLayout/projects",
      "children": [
        "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId"
      ]
    },
    "/staff/_staffLayout/projects": {
      "filePath": "staff/_staffLayout/projects",
      "parent": "/staff/_staffLayout",
      "children": [
        "/staff/_staffLayout/projects/_allProjectsLayout",
        "/staff/_staffLayout/projects/"
      ]
    },
    "/staff/_staffLayout/projects/_allProjectsLayout": {
      "filePath": "staff/_staffLayout/projects/_allProjectsLayout.tsx",
      "parent": "/staff/_staffLayout/projects",
      "children": [
        "/staff/_staffLayout/projects/_allProjectsLayout/$projectId"
      ]
    },
    "/proponent/_proponentLayout/projects/": {
      "filePath": "proponent/_proponentLayout/projects/index.tsx",
      "parent": "/proponent/_proponentLayout/projects"
    },
    "/staff/_staffLayout/projects/": {
      "filePath": "staff/_staffLayout/projects/index.tsx",
      "parent": "/staff/_staffLayout/projects"
    },
    "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId": {
      "filePath": "proponent/_proponentLayout/projects/_allProjectsLayout/$projectId",
      "parent": "/proponent/_proponentLayout/projects/_allProjectsLayout",
      "children": [
        "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout"
      ]
    },
    "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout": {
      "filePath": "proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout.tsx",
      "parent": "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId",
      "children": [
        "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/new-submission",
        "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/",
        "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId"
      ]
    },
    "/staff/_staffLayout/projects/_allProjectsLayout/$projectId": {
      "filePath": "staff/_staffLayout/projects/_allProjectsLayout/$projectId",
      "parent": "/staff/_staffLayout/projects/_allProjectsLayout",
      "children": [
        "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout"
      ]
    },
    "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout": {
      "filePath": "staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout.tsx",
      "parent": "/staff/_staffLayout/projects/_allProjectsLayout/$projectId",
      "children": [
        "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/",
        "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId"
      ]
    },
    "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/new-submission": {
      "filePath": "proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/new-submission.tsx",
      "parent": "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout"
    },
    "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/": {
      "filePath": "proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/index.tsx",
      "parent": "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout"
    },
    "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/": {
      "filePath": "staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/index.tsx",
      "parent": "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout"
    },
    "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId": {
      "filePath": "proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "parent": "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout",
      "children": [
        "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
      ]
    },
    "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout": {
      "filePath": "proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout.tsx",
      "parent": "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "children": [
        "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/",
        "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId"
      ]
    },
    "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId": {
      "filePath": "staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "parent": "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout",
      "children": [
        "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
      ]
    },
    "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout": {
      "filePath": "staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout.tsx",
      "parent": "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "children": [
        "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/",
        "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId"
      ]
    },
    "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/": {
      "filePath": "proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index.tsx",
      "parent": "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    },
    "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/": {
      "filePath": "staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index.tsx",
      "parent": "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    },
    "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId": {
      "filePath": "proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId.tsx",
      "parent": "/proponent/_proponentLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    },
    "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId": {
      "filePath": "staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId.tsx",
      "parent": "/staff/_staffLayout/projects/_allProjectsLayout/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    }
  }
}
ROUTE_MANIFEST_END */
