/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as NeedAccessRouteImport } from './routes/need-access'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as ProponentIndexRouteImport } from './routes/proponent/index'
import { Route as OidcCallbackIndexRouteImport } from './routes/oidc-callback/index'
import { Route as StaffNoRolesRouteImport } from './routes/staff/no-roles'
import { Route as StaffStaffLayoutRouteImport } from './routes/staff/_staffLayout'
import { Route as ProponentProponentLayoutRouteImport } from './routes/proponent/_proponentLayout'
import { Route as ProponentAccountRegistrationRouteRouteImport } from './routes/proponent/account-registration/route'
import { Route as ProponentAccountRegistrationIndexRouteImport } from './routes/proponent/account-registration/index'
import { Route as ProponentAccountRegistrationSecondAdminRouteImport } from './routes/proponent/account-registration/second-admin'
import { Route as ProponentAccountRegistrationRegistrationErrorRouteImport } from './routes/proponent/account-registration/registration-error'
import { Route as ProponentAccountRegistrationCreateAccountRouteImport } from './routes/proponent/account-registration/create-account'
import { Route as ProponentAccountRegistrationConfirmProjectsRouteImport } from './routes/proponent/account-registration/confirm-projects'
import { Route as ProponentAccountRegistrationCompletedRouteImport } from './routes/proponent/account-registration/completed'
import { Route as ProponentProponentLayoutProfileRouteImport } from './routes/proponent/_proponentLayout/profile'
import { Route as StaffStaffLayoutProponentsIndexRouteImport } from './routes/staff/_staffLayout/proponents/index'
import { Route as StaffStaffLayoutProjectsIndexRouteImport } from './routes/staff/_staffLayout/projects/index'
import { Route as StaffStaffLayoutDocumentsIndexRouteImport } from './routes/staff/_staffLayout/documents/index'
import { Route as ProponentProponentLayoutUserManagementIndexRouteImport } from './routes/proponent/_proponentLayout/user-management/index'
import { Route as ProponentProponentLayoutProjectsIndexRouteImport } from './routes/proponent/_proponentLayout/projects/index'
import { Route as ProponentProponentLayoutDocumentsIndexRouteImport } from './routes/proponent/_proponentLayout/documents/index'
import { Route as StaffStaffLayoutProponentsProponentIdRouteImport } from './routes/staff/_staffLayout/proponents/$proponentId'
import { Route as ProponentProponentLayoutUserManagementUserDetailsRouteImport } from './routes/proponent/_proponentLayout/user-management/user-details'
import { Route as ProponentProponentLayoutUserManagementProfileRouteImport } from './routes/proponent/_proponentLayout/user-management/profile'
import { Route as ProponentProponentLayoutUserManagementNewUserRouteImport } from './routes/proponent/_proponentLayout/user-management/new-user'
import { Route as ProponentProponentLayoutUserManagementEditProfileRouteImport } from './routes/proponent/_proponentLayout/user-management/edit-profile'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutRouteImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRouteImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/index'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRouteImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout/index'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRouteImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRouteImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRouteImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutInternalDocumentsIndexRouteImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/internal-documents/index'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRouteImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRouteImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'

const ProponentProponentLayoutAboutpageLazyRouteImport = createFileRoute(
  '/proponent/_proponentLayout/aboutpage',
)()

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedAccessRoute = NeedAccessRouteImport.update({
  id: '/need-access',
  path: '/need-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProponentIndexRoute = ProponentIndexRouteImport.update({
  id: '/proponent/',
  path: '/proponent/',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcCallbackIndexRoute = OidcCallbackIndexRouteImport.update({
  id: '/oidc-callback/',
  path: '/oidc-callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffNoRolesRoute = StaffNoRolesRouteImport.update({
  id: '/staff/no-roles',
  path: '/staff/no-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffLayoutRoute = StaffStaffLayoutRouteImport.update({
  id: '/staff/_staffLayout',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ProponentProponentLayoutRoute =
  ProponentProponentLayoutRouteImport.update({
    id: '/proponent/_proponentLayout',
    path: '/proponent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProponentAccountRegistrationRouteRoute =
  ProponentAccountRegistrationRouteRouteImport.update({
    id: '/proponent/account-registration',
    path: '/proponent/account-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProponentAccountRegistrationIndexRoute =
  ProponentAccountRegistrationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProponentAccountRegistrationRouteRoute,
  } as any)
const ProponentProponentLayoutAboutpageLazyRoute =
  ProponentProponentLayoutAboutpageLazyRouteImport.update({
    id: '/aboutpage',
    path: '/aboutpage',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any).lazy(() =>
    import('./routes/proponent/_proponentLayout/aboutpage.lazy').then(
      (d) => d.Route,
    ),
  )
const ProponentAccountRegistrationSecondAdminRoute =
  ProponentAccountRegistrationSecondAdminRouteImport.update({
    id: '/second-admin',
    path: '/second-admin',
    getParentRoute: () => ProponentAccountRegistrationRouteRoute,
  } as any)
const ProponentAccountRegistrationRegistrationErrorRoute =
  ProponentAccountRegistrationRegistrationErrorRouteImport.update({
    id: '/registration-error',
    path: '/registration-error',
    getParentRoute: () => ProponentAccountRegistrationRouteRoute,
  } as any)
const ProponentAccountRegistrationCreateAccountRoute =
  ProponentAccountRegistrationCreateAccountRouteImport.update({
    id: '/create-account',
    path: '/create-account',
    getParentRoute: () => ProponentAccountRegistrationRouteRoute,
  } as any)
const ProponentAccountRegistrationConfirmProjectsRoute =
  ProponentAccountRegistrationConfirmProjectsRouteImport.update({
    id: '/confirm-projects',
    path: '/confirm-projects',
    getParentRoute: () => ProponentAccountRegistrationRouteRoute,
  } as any)
const ProponentAccountRegistrationCompletedRoute =
  ProponentAccountRegistrationCompletedRouteImport.update({
    id: '/completed',
    path: '/completed',
    getParentRoute: () => ProponentAccountRegistrationRouteRoute,
  } as any)
const ProponentProponentLayoutProfileRoute =
  ProponentProponentLayoutProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)
const StaffStaffLayoutProponentsIndexRoute =
  StaffStaffLayoutProponentsIndexRouteImport.update({
    id: '/proponents/',
    path: '/proponents/',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)
const StaffStaffLayoutProjectsIndexRoute =
  StaffStaffLayoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)
const StaffStaffLayoutDocumentsIndexRoute =
  StaffStaffLayoutDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)
const ProponentProponentLayoutUserManagementIndexRoute =
  ProponentProponentLayoutUserManagementIndexRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)
const ProponentProponentLayoutProjectsIndexRoute =
  ProponentProponentLayoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)
const ProponentProponentLayoutDocumentsIndexRoute =
  ProponentProponentLayoutDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)
const StaffStaffLayoutProponentsProponentIdRoute =
  StaffStaffLayoutProponentsProponentIdRouteImport.update({
    id: '/proponents/$proponentId',
    path: '/proponents/$proponentId',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)
const ProponentProponentLayoutUserManagementUserDetailsRoute =
  ProponentProponentLayoutUserManagementUserDetailsRouteImport.update({
    id: '/user-management/user-details',
    path: '/user-management/user-details',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)
const ProponentProponentLayoutUserManagementProfileRoute =
  ProponentProponentLayoutUserManagementProfileRouteImport.update({
    id: '/user-management/profile',
    path: '/user-management/profile',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)
const ProponentProponentLayoutUserManagementNewUserRoute =
  ProponentProponentLayoutUserManagementNewUserRouteImport.update({
    id: '/user-management/new-user',
    path: '/user-management/new-user',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)
const ProponentProponentLayoutUserManagementEditProfileRoute =
  ProponentProponentLayoutUserManagementEditProfileRouteImport.update({
    id: '/user-management/edit-profile',
    path: '/user-management/edit-profile',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)
const StaffStaffLayoutProjectsProjectIdProjectLayoutRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutRouteImport.update({
    id: '/projects/$projectId/_projectLayout',
    path: '/projects/$projectId',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)
const ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteImport.update({
    id: '/projects/$projectId/_projectLayout',
    path: '/projects/$projectId',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)
const StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffLayoutProjectsProjectIdProjectLayoutRoute,
  } as any)
const ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute,
    } as any,
  )
const ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRouteImport.update(
    {
      id: '/new-submission',
      path: '/new-submission',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute,
    } as any,
  )
const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteImport.update(
    {
      id: '/submission-packages/$submissionPackageId/_submissionLayout',
      path: '/submission-packages/$submissionPackageId',
      getParentRoute: () => StaffStaffLayoutProjectsProjectIdProjectLayoutRoute,
    } as any,
  )
const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteImport.update(
    {
      id: '/submission-packages/$submissionPackageId/_submissionLayout',
      path: '/submission-packages/$submissionPackageId',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute,
    } as any,
  )
const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )
const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )
const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutInternalDocumentsIndexRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutInternalDocumentsIndexRouteImport.update(
    {
      id: '/internal-documents/',
      path: '/internal-documents/',
      getParentRoute: () =>
        StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )
const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRouteImport.update(
    {
      id: '/submissions/$submissionId',
      path: '/submissions/$submissionId',
      getParentRoute: () =>
        StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )
const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRouteImport.update(
    {
      id: '/submissions/$submissionId',
      path: '/submissions/$submissionId',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/need-access': typeof NeedAccessRoute
  '/not-found': typeof NotFoundRoute
  '/proponent/account-registration': typeof ProponentAccountRegistrationRouteRouteWithChildren
  '/proponent': typeof ProponentProponentLayoutRouteWithChildren
  '/staff': typeof StaffStaffLayoutRouteWithChildren
  '/staff/no-roles': typeof StaffNoRolesRoute
  '/oidc-callback/': typeof OidcCallbackIndexRoute
  '/proponent/': typeof ProponentIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/proponent/profile': typeof ProponentProponentLayoutProfileRoute
  '/proponent/account-registration/completed': typeof ProponentAccountRegistrationCompletedRoute
  '/proponent/account-registration/confirm-projects': typeof ProponentAccountRegistrationConfirmProjectsRoute
  '/proponent/account-registration/create-account': typeof ProponentAccountRegistrationCreateAccountRoute
  '/proponent/account-registration/registration-error': typeof ProponentAccountRegistrationRegistrationErrorRoute
  '/proponent/account-registration/second-admin': typeof ProponentAccountRegistrationSecondAdminRoute
  '/proponent/aboutpage': typeof ProponentProponentLayoutAboutpageLazyRoute
  '/proponent/account-registration/': typeof ProponentAccountRegistrationIndexRoute
  '/proponent/user-management/edit-profile': typeof ProponentProponentLayoutUserManagementEditProfileRoute
  '/proponent/user-management/new-user': typeof ProponentProponentLayoutUserManagementNewUserRoute
  '/proponent/user-management/profile': typeof ProponentProponentLayoutUserManagementProfileRoute
  '/proponent/user-management/user-details': typeof ProponentProponentLayoutUserManagementUserDetailsRoute
  '/staff/proponents/$proponentId': typeof StaffStaffLayoutProponentsProponentIdRoute
  '/proponent/documents/': typeof ProponentProponentLayoutDocumentsIndexRoute
  '/proponent/projects/': typeof ProponentProponentLayoutProjectsIndexRoute
  '/proponent/user-management/': typeof ProponentProponentLayoutUserManagementIndexRoute
  '/staff/documents/': typeof StaffStaffLayoutDocumentsIndexRoute
  '/staff/projects/': typeof StaffStaffLayoutProjectsIndexRoute
  '/staff/proponents/': typeof StaffStaffLayoutProponentsIndexRoute
  '/proponent/projects/$projectId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteWithChildren
  '/staff/projects/$projectId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutRouteWithChildren
  '/proponent/projects/$projectId/new-submission': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute
  '/proponent/projects/$projectId/': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/staff/projects/$projectId/': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/proponent/projects/$projectId/submission-packages/$submissionPackageId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
  '/staff/projects/$projectId/submission-packages/$submissionPackageId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
  '/proponent/projects/$projectId/submission-packages/$submissionPackageId/': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/staff/projects/$projectId/submission-packages/$submissionPackageId/': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
  '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
  '/staff/projects/$projectId/submission-packages/$submissionPackageId/internal-documents/': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutInternalDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/need-access': typeof NeedAccessRoute
  '/not-found': typeof NotFoundRoute
  '/proponent': typeof ProponentIndexRoute
  '/staff': typeof StaffIndexRoute
  '/staff/no-roles': typeof StaffNoRolesRoute
  '/oidc-callback': typeof OidcCallbackIndexRoute
  '/proponent/profile': typeof ProponentProponentLayoutProfileRoute
  '/proponent/account-registration/completed': typeof ProponentAccountRegistrationCompletedRoute
  '/proponent/account-registration/confirm-projects': typeof ProponentAccountRegistrationConfirmProjectsRoute
  '/proponent/account-registration/create-account': typeof ProponentAccountRegistrationCreateAccountRoute
  '/proponent/account-registration/registration-error': typeof ProponentAccountRegistrationRegistrationErrorRoute
  '/proponent/account-registration/second-admin': typeof ProponentAccountRegistrationSecondAdminRoute
  '/proponent/aboutpage': typeof ProponentProponentLayoutAboutpageLazyRoute
  '/proponent/account-registration': typeof ProponentAccountRegistrationIndexRoute
  '/proponent/user-management/edit-profile': typeof ProponentProponentLayoutUserManagementEditProfileRoute
  '/proponent/user-management/new-user': typeof ProponentProponentLayoutUserManagementNewUserRoute
  '/proponent/user-management/profile': typeof ProponentProponentLayoutUserManagementProfileRoute
  '/proponent/user-management/user-details': typeof ProponentProponentLayoutUserManagementUserDetailsRoute
  '/staff/proponents/$proponentId': typeof StaffStaffLayoutProponentsProponentIdRoute
  '/proponent/documents': typeof ProponentProponentLayoutDocumentsIndexRoute
  '/proponent/projects': typeof ProponentProponentLayoutProjectsIndexRoute
  '/proponent/user-management': typeof ProponentProponentLayoutUserManagementIndexRoute
  '/staff/documents': typeof StaffStaffLayoutDocumentsIndexRoute
  '/staff/projects': typeof StaffStaffLayoutProjectsIndexRoute
  '/staff/proponents': typeof StaffStaffLayoutProponentsIndexRoute
  '/proponent/projects/$projectId/new-submission': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute
  '/proponent/projects/$projectId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/staff/projects/$projectId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/proponent/projects/$projectId/submission-packages/$submissionPackageId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/staff/projects/$projectId/submission-packages/$submissionPackageId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
  '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
  '/staff/projects/$projectId/submission-packages/$submissionPackageId/internal-documents': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutInternalDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/need-access': typeof NeedAccessRoute
  '/not-found': typeof NotFoundRoute
  '/proponent/account-registration': typeof ProponentAccountRegistrationRouteRouteWithChildren
  '/proponent/_proponentLayout': typeof ProponentProponentLayoutRouteWithChildren
  '/staff/_staffLayout': typeof StaffStaffLayoutRouteWithChildren
  '/staff/no-roles': typeof StaffNoRolesRoute
  '/oidc-callback/': typeof OidcCallbackIndexRoute
  '/proponent/': typeof ProponentIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/proponent/_proponentLayout/profile': typeof ProponentProponentLayoutProfileRoute
  '/proponent/account-registration/completed': typeof ProponentAccountRegistrationCompletedRoute
  '/proponent/account-registration/confirm-projects': typeof ProponentAccountRegistrationConfirmProjectsRoute
  '/proponent/account-registration/create-account': typeof ProponentAccountRegistrationCreateAccountRoute
  '/proponent/account-registration/registration-error': typeof ProponentAccountRegistrationRegistrationErrorRoute
  '/proponent/account-registration/second-admin': typeof ProponentAccountRegistrationSecondAdminRoute
  '/proponent/_proponentLayout/aboutpage': typeof ProponentProponentLayoutAboutpageLazyRoute
  '/proponent/account-registration/': typeof ProponentAccountRegistrationIndexRoute
  '/proponent/_proponentLayout/user-management/edit-profile': typeof ProponentProponentLayoutUserManagementEditProfileRoute
  '/proponent/_proponentLayout/user-management/new-user': typeof ProponentProponentLayoutUserManagementNewUserRoute
  '/proponent/_proponentLayout/user-management/profile': typeof ProponentProponentLayoutUserManagementProfileRoute
  '/proponent/_proponentLayout/user-management/user-details': typeof ProponentProponentLayoutUserManagementUserDetailsRoute
  '/staff/_staffLayout/proponents/$proponentId': typeof StaffStaffLayoutProponentsProponentIdRoute
  '/proponent/_proponentLayout/documents/': typeof ProponentProponentLayoutDocumentsIndexRoute
  '/proponent/_proponentLayout/projects/': typeof ProponentProponentLayoutProjectsIndexRoute
  '/proponent/_proponentLayout/user-management/': typeof ProponentProponentLayoutUserManagementIndexRoute
  '/staff/_staffLayout/documents/': typeof StaffStaffLayoutDocumentsIndexRoute
  '/staff/_staffLayout/projects/': typeof StaffStaffLayoutProjectsIndexRoute
  '/staff/_staffLayout/proponents/': typeof StaffStaffLayoutProponentsIndexRoute
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteWithChildren
  '/staff/_staffLayout/projects/$projectId/_projectLayout': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutRouteWithChildren
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout/': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/staff/_staffLayout/projects/$projectId/_projectLayout/': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
  '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
  '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
  '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/internal-documents/': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutInternalDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/login'
    | '/logout'
    | '/need-access'
    | '/not-found'
    | '/proponent/account-registration'
    | '/proponent'
    | '/staff'
    | '/staff/no-roles'
    | '/oidc-callback/'
    | '/proponent/'
    | '/staff/'
    | '/proponent/profile'
    | '/proponent/account-registration/completed'
    | '/proponent/account-registration/confirm-projects'
    | '/proponent/account-registration/create-account'
    | '/proponent/account-registration/registration-error'
    | '/proponent/account-registration/second-admin'
    | '/proponent/aboutpage'
    | '/proponent/account-registration/'
    | '/proponent/user-management/edit-profile'
    | '/proponent/user-management/new-user'
    | '/proponent/user-management/profile'
    | '/proponent/user-management/user-details'
    | '/staff/proponents/$proponentId'
    | '/proponent/documents/'
    | '/proponent/projects/'
    | '/proponent/user-management/'
    | '/staff/documents/'
    | '/staff/projects/'
    | '/staff/proponents/'
    | '/proponent/projects/$projectId'
    | '/staff/projects/$projectId'
    | '/proponent/projects/$projectId/new-submission'
    | '/proponent/projects/$projectId/'
    | '/staff/projects/$projectId/'
    | '/proponent/projects/$projectId/submission-packages/$submissionPackageId'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId'
    | '/proponent/projects/$projectId/submission-packages/$submissionPackageId/'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId/'
    | '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId/internal-documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/login'
    | '/logout'
    | '/need-access'
    | '/not-found'
    | '/proponent'
    | '/staff'
    | '/staff/no-roles'
    | '/oidc-callback'
    | '/proponent/profile'
    | '/proponent/account-registration/completed'
    | '/proponent/account-registration/confirm-projects'
    | '/proponent/account-registration/create-account'
    | '/proponent/account-registration/registration-error'
    | '/proponent/account-registration/second-admin'
    | '/proponent/aboutpage'
    | '/proponent/account-registration'
    | '/proponent/user-management/edit-profile'
    | '/proponent/user-management/new-user'
    | '/proponent/user-management/profile'
    | '/proponent/user-management/user-details'
    | '/staff/proponents/$proponentId'
    | '/proponent/documents'
    | '/proponent/projects'
    | '/proponent/user-management'
    | '/staff/documents'
    | '/staff/projects'
    | '/staff/proponents'
    | '/proponent/projects/$projectId/new-submission'
    | '/proponent/projects/$projectId'
    | '/staff/projects/$projectId'
    | '/proponent/projects/$projectId/submission-packages/$submissionPackageId'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId'
    | '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId/internal-documents'
  id:
    | '__root__'
    | '/'
    | '/error'
    | '/login'
    | '/logout'
    | '/need-access'
    | '/not-found'
    | '/proponent/account-registration'
    | '/proponent/_proponentLayout'
    | '/staff/_staffLayout'
    | '/staff/no-roles'
    | '/oidc-callback/'
    | '/proponent/'
    | '/staff/'
    | '/proponent/_proponentLayout/profile'
    | '/proponent/account-registration/completed'
    | '/proponent/account-registration/confirm-projects'
    | '/proponent/account-registration/create-account'
    | '/proponent/account-registration/registration-error'
    | '/proponent/account-registration/second-admin'
    | '/proponent/_proponentLayout/aboutpage'
    | '/proponent/account-registration/'
    | '/proponent/_proponentLayout/user-management/edit-profile'
    | '/proponent/_proponentLayout/user-management/new-user'
    | '/proponent/_proponentLayout/user-management/profile'
    | '/proponent/_proponentLayout/user-management/user-details'
    | '/staff/_staffLayout/proponents/$proponentId'
    | '/proponent/_proponentLayout/documents/'
    | '/proponent/_proponentLayout/projects/'
    | '/proponent/_proponentLayout/user-management/'
    | '/staff/_staffLayout/documents/'
    | '/staff/_staffLayout/projects/'
    | '/staff/_staffLayout/proponents/'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout/'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout/'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/internal-documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  NeedAccessRoute: typeof NeedAccessRoute
  NotFoundRoute: typeof NotFoundRoute
  ProponentAccountRegistrationRouteRoute: typeof ProponentAccountRegistrationRouteRouteWithChildren
  ProponentProponentLayoutRoute: typeof ProponentProponentLayoutRouteWithChildren
  StaffStaffLayoutRoute: typeof StaffStaffLayoutRouteWithChildren
  StaffNoRolesRoute: typeof StaffNoRolesRoute
  OidcCallbackIndexRoute: typeof OidcCallbackIndexRoute
  ProponentIndexRoute: typeof ProponentIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/need-access': {
      id: '/need-access'
      path: '/need-access'
      fullPath: '/need-access'
      preLoaderRoute: typeof NeedAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proponent/': {
      id: '/proponent/'
      path: '/proponent'
      fullPath: '/proponent/'
      preLoaderRoute: typeof ProponentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc-callback/': {
      id: '/oidc-callback/'
      path: '/oidc-callback'
      fullPath: '/oidc-callback/'
      preLoaderRoute: typeof OidcCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/no-roles': {
      id: '/staff/no-roles'
      path: '/staff/no-roles'
      fullPath: '/staff/no-roles'
      preLoaderRoute: typeof StaffNoRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/_staffLayout': {
      id: '/staff/_staffLayout'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffStaffLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proponent/_proponentLayout': {
      id: '/proponent/_proponentLayout'
      path: '/proponent'
      fullPath: '/proponent'
      preLoaderRoute: typeof ProponentProponentLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proponent/account-registration': {
      id: '/proponent/account-registration'
      path: '/proponent/account-registration'
      fullPath: '/proponent/account-registration'
      preLoaderRoute: typeof ProponentAccountRegistrationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proponent/account-registration/': {
      id: '/proponent/account-registration/'
      path: '/'
      fullPath: '/proponent/account-registration/'
      preLoaderRoute: typeof ProponentAccountRegistrationIndexRouteImport
      parentRoute: typeof ProponentAccountRegistrationRouteRoute
    }
    '/proponent/_proponentLayout/aboutpage': {
      id: '/proponent/_proponentLayout/aboutpage'
      path: '/aboutpage'
      fullPath: '/proponent/aboutpage'
      preLoaderRoute: typeof ProponentProponentLayoutAboutpageLazyRouteImport
      parentRoute: typeof ProponentProponentLayoutRoute
    }
    '/proponent/account-registration/second-admin': {
      id: '/proponent/account-registration/second-admin'
      path: '/second-admin'
      fullPath: '/proponent/account-registration/second-admin'
      preLoaderRoute: typeof ProponentAccountRegistrationSecondAdminRouteImport
      parentRoute: typeof ProponentAccountRegistrationRouteRoute
    }
    '/proponent/account-registration/registration-error': {
      id: '/proponent/account-registration/registration-error'
      path: '/registration-error'
      fullPath: '/proponent/account-registration/registration-error'
      preLoaderRoute: typeof ProponentAccountRegistrationRegistrationErrorRouteImport
      parentRoute: typeof ProponentAccountRegistrationRouteRoute
    }
    '/proponent/account-registration/create-account': {
      id: '/proponent/account-registration/create-account'
      path: '/create-account'
      fullPath: '/proponent/account-registration/create-account'
      preLoaderRoute: typeof ProponentAccountRegistrationCreateAccountRouteImport
      parentRoute: typeof ProponentAccountRegistrationRouteRoute
    }
    '/proponent/account-registration/confirm-projects': {
      id: '/proponent/account-registration/confirm-projects'
      path: '/confirm-projects'
      fullPath: '/proponent/account-registration/confirm-projects'
      preLoaderRoute: typeof ProponentAccountRegistrationConfirmProjectsRouteImport
      parentRoute: typeof ProponentAccountRegistrationRouteRoute
    }
    '/proponent/account-registration/completed': {
      id: '/proponent/account-registration/completed'
      path: '/completed'
      fullPath: '/proponent/account-registration/completed'
      preLoaderRoute: typeof ProponentAccountRegistrationCompletedRouteImport
      parentRoute: typeof ProponentAccountRegistrationRouteRoute
    }
    '/proponent/_proponentLayout/profile': {
      id: '/proponent/_proponentLayout/profile'
      path: '/profile'
      fullPath: '/proponent/profile'
      preLoaderRoute: typeof ProponentProponentLayoutProfileRouteImport
      parentRoute: typeof ProponentProponentLayoutRoute
    }
    '/staff/_staffLayout/proponents/': {
      id: '/staff/_staffLayout/proponents/'
      path: '/proponents'
      fullPath: '/staff/proponents/'
      preLoaderRoute: typeof StaffStaffLayoutProponentsIndexRouteImport
      parentRoute: typeof StaffStaffLayoutRoute
    }
    '/staff/_staffLayout/projects/': {
      id: '/staff/_staffLayout/projects/'
      path: '/projects'
      fullPath: '/staff/projects/'
      preLoaderRoute: typeof StaffStaffLayoutProjectsIndexRouteImport
      parentRoute: typeof StaffStaffLayoutRoute
    }
    '/staff/_staffLayout/documents/': {
      id: '/staff/_staffLayout/documents/'
      path: '/documents'
      fullPath: '/staff/documents/'
      preLoaderRoute: typeof StaffStaffLayoutDocumentsIndexRouteImport
      parentRoute: typeof StaffStaffLayoutRoute
    }
    '/proponent/_proponentLayout/user-management/': {
      id: '/proponent/_proponentLayout/user-management/'
      path: '/user-management'
      fullPath: '/proponent/user-management/'
      preLoaderRoute: typeof ProponentProponentLayoutUserManagementIndexRouteImport
      parentRoute: typeof ProponentProponentLayoutRoute
    }
    '/proponent/_proponentLayout/projects/': {
      id: '/proponent/_proponentLayout/projects/'
      path: '/projects'
      fullPath: '/proponent/projects/'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsIndexRouteImport
      parentRoute: typeof ProponentProponentLayoutRoute
    }
    '/proponent/_proponentLayout/documents/': {
      id: '/proponent/_proponentLayout/documents/'
      path: '/documents'
      fullPath: '/proponent/documents/'
      preLoaderRoute: typeof ProponentProponentLayoutDocumentsIndexRouteImport
      parentRoute: typeof ProponentProponentLayoutRoute
    }
    '/staff/_staffLayout/proponents/$proponentId': {
      id: '/staff/_staffLayout/proponents/$proponentId'
      path: '/proponents/$proponentId'
      fullPath: '/staff/proponents/$proponentId'
      preLoaderRoute: typeof StaffStaffLayoutProponentsProponentIdRouteImport
      parentRoute: typeof StaffStaffLayoutRoute
    }
    '/proponent/_proponentLayout/user-management/user-details': {
      id: '/proponent/_proponentLayout/user-management/user-details'
      path: '/user-management/user-details'
      fullPath: '/proponent/user-management/user-details'
      preLoaderRoute: typeof ProponentProponentLayoutUserManagementUserDetailsRouteImport
      parentRoute: typeof ProponentProponentLayoutRoute
    }
    '/proponent/_proponentLayout/user-management/profile': {
      id: '/proponent/_proponentLayout/user-management/profile'
      path: '/user-management/profile'
      fullPath: '/proponent/user-management/profile'
      preLoaderRoute: typeof ProponentProponentLayoutUserManagementProfileRouteImport
      parentRoute: typeof ProponentProponentLayoutRoute
    }
    '/proponent/_proponentLayout/user-management/new-user': {
      id: '/proponent/_proponentLayout/user-management/new-user'
      path: '/user-management/new-user'
      fullPath: '/proponent/user-management/new-user'
      preLoaderRoute: typeof ProponentProponentLayoutUserManagementNewUserRouteImport
      parentRoute: typeof ProponentProponentLayoutRoute
    }
    '/proponent/_proponentLayout/user-management/edit-profile': {
      id: '/proponent/_proponentLayout/user-management/edit-profile'
      path: '/user-management/edit-profile'
      fullPath: '/proponent/user-management/edit-profile'
      preLoaderRoute: typeof ProponentProponentLayoutUserManagementEditProfileRouteImport
      parentRoute: typeof ProponentProponentLayoutRoute
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout'
      path: '/projects/$projectId'
      fullPath: '/staff/projects/$projectId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutRouteImport
      parentRoute: typeof StaffStaffLayoutRoute
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout'
      path: '/projects/$projectId'
      fullPath: '/proponent/projects/$projectId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteImport
      parentRoute: typeof ProponentProponentLayoutRoute
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/'
      path: '/'
      fullPath: '/staff/projects/$projectId/'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRouteImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutRoute
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout/'
      path: '/'
      fullPath: '/proponent/projects/$projectId/'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRouteImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission'
      path: '/new-submission'
      fullPath: '/proponent/projects/$projectId/new-submission'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRouteImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutRoute
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
      path: '/'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId/'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRouteImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
      path: '/'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId/'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRouteImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/internal-documents/': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/internal-documents/'
      path: '/internal-documents'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId/internal-documents/'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutInternalDocumentsIndexRouteImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRouteImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRouteImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute
    }
  }
}

interface ProponentAccountRegistrationRouteRouteChildren {
  ProponentAccountRegistrationCompletedRoute: typeof ProponentAccountRegistrationCompletedRoute
  ProponentAccountRegistrationConfirmProjectsRoute: typeof ProponentAccountRegistrationConfirmProjectsRoute
  ProponentAccountRegistrationCreateAccountRoute: typeof ProponentAccountRegistrationCreateAccountRoute
  ProponentAccountRegistrationRegistrationErrorRoute: typeof ProponentAccountRegistrationRegistrationErrorRoute
  ProponentAccountRegistrationSecondAdminRoute: typeof ProponentAccountRegistrationSecondAdminRoute
  ProponentAccountRegistrationIndexRoute: typeof ProponentAccountRegistrationIndexRoute
}

const ProponentAccountRegistrationRouteRouteChildren: ProponentAccountRegistrationRouteRouteChildren =
  {
    ProponentAccountRegistrationCompletedRoute:
      ProponentAccountRegistrationCompletedRoute,
    ProponentAccountRegistrationConfirmProjectsRoute:
      ProponentAccountRegistrationConfirmProjectsRoute,
    ProponentAccountRegistrationCreateAccountRoute:
      ProponentAccountRegistrationCreateAccountRoute,
    ProponentAccountRegistrationRegistrationErrorRoute:
      ProponentAccountRegistrationRegistrationErrorRoute,
    ProponentAccountRegistrationSecondAdminRoute:
      ProponentAccountRegistrationSecondAdminRoute,
    ProponentAccountRegistrationIndexRoute:
      ProponentAccountRegistrationIndexRoute,
  }

const ProponentAccountRegistrationRouteRouteWithChildren =
  ProponentAccountRegistrationRouteRoute._addFileChildren(
    ProponentAccountRegistrationRouteRouteChildren,
  )

interface ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren {
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
}

const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren: ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren =
  {
    ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute,
    ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute,
  }

const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute._addFileChildren(
    ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren,
  )

interface ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteChildren {
  ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute
  ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
}

const ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteChildren: ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteChildren =
  {
    ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute,
    ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute,
    ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren,
  }

const ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteWithChildren =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute._addFileChildren(
    ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteChildren,
  )

interface ProponentProponentLayoutRouteChildren {
  ProponentProponentLayoutProfileRoute: typeof ProponentProponentLayoutProfileRoute
  ProponentProponentLayoutAboutpageLazyRoute: typeof ProponentProponentLayoutAboutpageLazyRoute
  ProponentProponentLayoutUserManagementEditProfileRoute: typeof ProponentProponentLayoutUserManagementEditProfileRoute
  ProponentProponentLayoutUserManagementNewUserRoute: typeof ProponentProponentLayoutUserManagementNewUserRoute
  ProponentProponentLayoutUserManagementProfileRoute: typeof ProponentProponentLayoutUserManagementProfileRoute
  ProponentProponentLayoutUserManagementUserDetailsRoute: typeof ProponentProponentLayoutUserManagementUserDetailsRoute
  ProponentProponentLayoutDocumentsIndexRoute: typeof ProponentProponentLayoutDocumentsIndexRoute
  ProponentProponentLayoutProjectsIndexRoute: typeof ProponentProponentLayoutProjectsIndexRoute
  ProponentProponentLayoutUserManagementIndexRoute: typeof ProponentProponentLayoutUserManagementIndexRoute
  ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteWithChildren
}

const ProponentProponentLayoutRouteChildren: ProponentProponentLayoutRouteChildren =
  {
    ProponentProponentLayoutProfileRoute: ProponentProponentLayoutProfileRoute,
    ProponentProponentLayoutAboutpageLazyRoute:
      ProponentProponentLayoutAboutpageLazyRoute,
    ProponentProponentLayoutUserManagementEditProfileRoute:
      ProponentProponentLayoutUserManagementEditProfileRoute,
    ProponentProponentLayoutUserManagementNewUserRoute:
      ProponentProponentLayoutUserManagementNewUserRoute,
    ProponentProponentLayoutUserManagementProfileRoute:
      ProponentProponentLayoutUserManagementProfileRoute,
    ProponentProponentLayoutUserManagementUserDetailsRoute:
      ProponentProponentLayoutUserManagementUserDetailsRoute,
    ProponentProponentLayoutDocumentsIndexRoute:
      ProponentProponentLayoutDocumentsIndexRoute,
    ProponentProponentLayoutProjectsIndexRoute:
      ProponentProponentLayoutProjectsIndexRoute,
    ProponentProponentLayoutUserManagementIndexRoute:
      ProponentProponentLayoutUserManagementIndexRoute,
    ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteWithChildren,
  }

const ProponentProponentLayoutRouteWithChildren =
  ProponentProponentLayoutRoute._addFileChildren(
    ProponentProponentLayoutRouteChildren,
  )

interface StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren {
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutInternalDocumentsIndexRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutInternalDocumentsIndexRoute
}

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren: StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren =
  {
    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute:
      StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute,
    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute:
      StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute,
    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutInternalDocumentsIndexRoute:
      StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutInternalDocumentsIndexRoute,
  }

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute._addFileChildren(
    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren,
  )

interface StaffStaffLayoutProjectsProjectIdProjectLayoutRouteChildren {
  StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
}

const StaffStaffLayoutProjectsProjectIdProjectLayoutRouteChildren: StaffStaffLayoutProjectsProjectIdProjectLayoutRouteChildren =
  {
    StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute:
      StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute,
    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute:
      StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren,
  }

const StaffStaffLayoutProjectsProjectIdProjectLayoutRouteWithChildren =
  StaffStaffLayoutProjectsProjectIdProjectLayoutRoute._addFileChildren(
    StaffStaffLayoutProjectsProjectIdProjectLayoutRouteChildren,
  )

interface StaffStaffLayoutRouteChildren {
  StaffStaffLayoutProponentsProponentIdRoute: typeof StaffStaffLayoutProponentsProponentIdRoute
  StaffStaffLayoutDocumentsIndexRoute: typeof StaffStaffLayoutDocumentsIndexRoute
  StaffStaffLayoutProjectsIndexRoute: typeof StaffStaffLayoutProjectsIndexRoute
  StaffStaffLayoutProponentsIndexRoute: typeof StaffStaffLayoutProponentsIndexRoute
  StaffStaffLayoutProjectsProjectIdProjectLayoutRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutRouteWithChildren
}

const StaffStaffLayoutRouteChildren: StaffStaffLayoutRouteChildren = {
  StaffStaffLayoutProponentsProponentIdRoute:
    StaffStaffLayoutProponentsProponentIdRoute,
  StaffStaffLayoutDocumentsIndexRoute: StaffStaffLayoutDocumentsIndexRoute,
  StaffStaffLayoutProjectsIndexRoute: StaffStaffLayoutProjectsIndexRoute,
  StaffStaffLayoutProponentsIndexRoute: StaffStaffLayoutProponentsIndexRoute,
  StaffStaffLayoutProjectsProjectIdProjectLayoutRoute:
    StaffStaffLayoutProjectsProjectIdProjectLayoutRouteWithChildren,
}

const StaffStaffLayoutRouteWithChildren =
  StaffStaffLayoutRoute._addFileChildren(StaffStaffLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  NeedAccessRoute: NeedAccessRoute,
  NotFoundRoute: NotFoundRoute,
  ProponentAccountRegistrationRouteRoute:
    ProponentAccountRegistrationRouteRouteWithChildren,
  ProponentProponentLayoutRoute: ProponentProponentLayoutRouteWithChildren,
  StaffStaffLayoutRoute: StaffStaffLayoutRouteWithChildren,
  StaffNoRolesRoute: StaffNoRolesRoute,
  OidcCallbackIndexRoute: OidcCallbackIndexRoute,
  ProponentIndexRoute: ProponentIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
