/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as ErrorImport } from './routes/error'
import { Route as IndexImport } from './routes/index'
import { Route as OidcCallbackIndexImport } from './routes/oidc-callback/index'
import { Route as StaffStaffLayoutImport } from './routes/staff/_staffLayout'
import { Route as ProponentProponentLayoutImport } from './routes/proponent/_proponentLayout'
import { Route as ProponentRegistrationIndexImport } from './routes/proponent/registration/index'
import { Route as ProponentRegistrationCreateAccountImport } from './routes/proponent/registration/create-account'
import { Route as ProponentRegistrationCompleteImport } from './routes/proponent/registration/complete'
import { Route as ProponentProponentLayoutAdminLoginImport } from './routes/proponent/_proponentLayout/admin-login'
import { Route as ProponentProponentLayoutDashboardImport } from './routes/proponent/_proponentLayout/_dashboard'
import { Route as StaffStaffLayoutProjectsIndexImport } from './routes/staff/_staffLayout/projects/index'
import { Route as ProponentProponentLayoutDashboardProfileImport } from './routes/proponent/_proponentLayout/_dashboard/profile'
import { Route as ProponentProponentLayoutDashboardProjectsIndexImport } from './routes/proponent/_proponentLayout/_dashboard/projects/index'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutIndexImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/index'
import { Route as ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutImport } from './routes/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout'
import { Route as ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutIndexImport } from './routes/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/index'
import { Route as ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutNewSubmissionImport } from './routes/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/new-submission'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index'
import { Route as ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport } from './routes/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
import { Route as ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport } from './routes/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
import { Route as ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport } from './routes/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'

// Create Virtual Routes

const StaffImport = createFileRoute('/staff')()
const ProponentImport = createFileRoute('/proponent')()
const StaffStaffLayoutProjectsProjectIdImport = createFileRoute(
  '/staff/_staffLayout/projects/$projectId',
)()
const ProponentProponentLayoutDashboardAboutpageLazyImport = createFileRoute(
  '/proponent/_proponentLayout/_dashboard/aboutpage',
)()
const ProponentProponentLayoutDashboardProjectsProjectIdImport =
  createFileRoute(
    '/proponent/_proponentLayout/_dashboard/projects/$projectId',
  )()
const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport =
  createFileRoute(
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId',
  )()
const ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport =
  createFileRoute(
    '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId',
  )()

// Create/Update Routes

const StaffRoute = StaffImport.update({
  path: '/staff',
  getParentRoute: () => rootRoute,
} as any)

const ProponentRoute = ProponentImport.update({
  path: '/proponent',
  getParentRoute: () => rootRoute,
} as any)

const NotFoundRoute = NotFoundImport.update({
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OidcCallbackIndexRoute = OidcCallbackIndexImport.update({
  path: '/oidc-callback/',
  getParentRoute: () => rootRoute,
} as any)

const StaffStaffLayoutRoute = StaffStaffLayoutImport.update({
  id: '/_staffLayout',
  getParentRoute: () => StaffRoute,
} as any)

const ProponentProponentLayoutRoute = ProponentProponentLayoutImport.update({
  id: '/_proponentLayout',
  getParentRoute: () => ProponentRoute,
} as any)

const ProponentRegistrationIndexRoute = ProponentRegistrationIndexImport.update(
  {
    path: '/registration/',
    getParentRoute: () => ProponentRoute,
  } as any,
)

const ProponentRegistrationCreateAccountRoute =
  ProponentRegistrationCreateAccountImport.update({
    path: '/registration/create-account',
    getParentRoute: () => ProponentRoute,
  } as any)

const ProponentRegistrationCompleteRoute =
  ProponentRegistrationCompleteImport.update({
    path: '/registration/complete',
    getParentRoute: () => ProponentRoute,
  } as any)

const ProponentProponentLayoutAdminLoginRoute =
  ProponentProponentLayoutAdminLoginImport.update({
    path: '/admin-login',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const ProponentProponentLayoutDashboardRoute =
  ProponentProponentLayoutDashboardImport.update({
    id: '/_dashboard',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const StaffStaffLayoutProjectsProjectIdRoute =
  StaffStaffLayoutProjectsProjectIdImport.update({
    path: '/projects/$projectId',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)

const StaffStaffLayoutProjectsIndexRoute =
  StaffStaffLayoutProjectsIndexImport.update({
    path: '/projects/',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)

const ProponentProponentLayoutDashboardAboutpageLazyRoute =
  ProponentProponentLayoutDashboardAboutpageLazyImport.update({
    path: '/aboutpage',
    getParentRoute: () => ProponentProponentLayoutDashboardRoute,
  } as any).lazy(() =>
    import(
      './routes/proponent/_proponentLayout/_dashboard/aboutpage.lazy'
    ).then((d) => d.Route),
  )

const ProponentProponentLayoutDashboardProfileRoute =
  ProponentProponentLayoutDashboardProfileImport.update({
    path: '/profile',
    getParentRoute: () => ProponentProponentLayoutDashboardRoute,
  } as any)

const ProponentProponentLayoutDashboardProjectsProjectIdRoute =
  ProponentProponentLayoutDashboardProjectsProjectIdImport.update({
    path: '/projects/$projectId',
    getParentRoute: () => ProponentProponentLayoutDashboardRoute,
  } as any)

const ProponentProponentLayoutDashboardProjectsIndexRoute =
  ProponentProponentLayoutDashboardProjectsIndexImport.update({
    path: '/projects/',
    getParentRoute: () => ProponentProponentLayoutDashboardRoute,
  } as any)

const StaffStaffLayoutProjectsProjectIdProjectLayoutRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutImport.update({
    id: '/_projectLayout',
    getParentRoute: () => StaffStaffLayoutProjectsProjectIdRoute,
  } as any)

const StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => StaffStaffLayoutProjectsProjectIdProjectLayoutRoute,
  } as any)

const ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutRoute =
  ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutImport.update({
    id: '/_projectLayout',
    getParentRoute: () =>
      ProponentProponentLayoutDashboardProjectsProjectIdRoute,
  } as any)

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport.update(
    {
      path: '/submission-packages/$submissionPackageId',
      getParentRoute: () => StaffStaffLayoutProjectsProjectIdProjectLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutIndexRoute =
  ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutIndexImport.update(
    {
      path: '/',
      getParentRoute: () =>
        ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutNewSubmissionRoute =
  ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutNewSubmissionImport.update(
    {
      path: '/new-submission',
      getParentRoute: () =>
        ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute =
  ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport.update(
    {
      path: '/submission-packages/$submissionPackageId',
      getParentRoute: () =>
        ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutRoute,
    } as any,
  )

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport.update(
    {
      id: '/_submissionLayout',
      getParentRoute: () =>
        StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute,
    } as any,
  )

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport.update(
    {
      path: '/',
      getParentRoute: () =>
        StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute =
  ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport.update(
    {
      id: '/_submissionLayout',
      getParentRoute: () =>
        ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute,
    } as any,
  )

const ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute =
  ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport.update(
    {
      path: '/',
      getParentRoute: () =>
        ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport.update(
    {
      path: '/submissions/$submissionId',
      getParentRoute: () =>
        StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute =
  ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport.update(
    {
      path: '/submissions/$submissionId',
      getParentRoute: () =>
        ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/proponent': {
      id: '/proponent'
      path: '/proponent'
      fullPath: '/proponent'
      preLoaderRoute: typeof ProponentImport
      parentRoute: typeof rootRoute
    }
    '/proponent/_proponentLayout': {
      id: '/proponent/_proponentLayout'
      path: '/proponent'
      fullPath: '/proponent'
      preLoaderRoute: typeof ProponentProponentLayoutImport
      parentRoute: typeof ProponentRoute
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffImport
      parentRoute: typeof rootRoute
    }
    '/staff/_staffLayout': {
      id: '/staff/_staffLayout'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffStaffLayoutImport
      parentRoute: typeof StaffRoute
    }
    '/oidc-callback/': {
      id: '/oidc-callback/'
      path: '/oidc-callback'
      fullPath: '/oidc-callback'
      preLoaderRoute: typeof OidcCallbackIndexImport
      parentRoute: typeof rootRoute
    }
    '/proponent/_proponentLayout/_dashboard': {
      id: '/proponent/_proponentLayout/_dashboard'
      path: ''
      fullPath: '/proponent'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/_proponentLayout/admin-login': {
      id: '/proponent/_proponentLayout/admin-login'
      path: '/admin-login'
      fullPath: '/proponent/admin-login'
      preLoaderRoute: typeof ProponentProponentLayoutAdminLoginImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/registration/complete': {
      id: '/proponent/registration/complete'
      path: '/registration/complete'
      fullPath: '/proponent/registration/complete'
      preLoaderRoute: typeof ProponentRegistrationCompleteImport
      parentRoute: typeof ProponentImport
    }
    '/proponent/registration/create-account': {
      id: '/proponent/registration/create-account'
      path: '/registration/create-account'
      fullPath: '/proponent/registration/create-account'
      preLoaderRoute: typeof ProponentRegistrationCreateAccountImport
      parentRoute: typeof ProponentImport
    }
    '/proponent/registration/': {
      id: '/proponent/registration/'
      path: '/registration'
      fullPath: '/proponent/registration'
      preLoaderRoute: typeof ProponentRegistrationIndexImport
      parentRoute: typeof ProponentImport
    }
    '/proponent/_proponentLayout/_dashboard/profile': {
      id: '/proponent/_proponentLayout/_dashboard/profile'
      path: '/profile'
      fullPath: '/proponent/profile'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardProfileImport
      parentRoute: typeof ProponentProponentLayoutDashboardImport
    }
    '/proponent/_proponentLayout/_dashboard/aboutpage': {
      id: '/proponent/_proponentLayout/_dashboard/aboutpage'
      path: '/aboutpage'
      fullPath: '/proponent/aboutpage'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardAboutpageLazyImport
      parentRoute: typeof ProponentProponentLayoutDashboardImport
    }
    '/staff/_staffLayout/projects/': {
      id: '/staff/_staffLayout/projects/'
      path: '/projects'
      fullPath: '/staff/projects'
      preLoaderRoute: typeof StaffStaffLayoutProjectsIndexImport
      parentRoute: typeof StaffStaffLayoutImport
    }
    '/staff/_staffLayout/projects/$projectId': {
      id: '/staff/_staffLayout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/staff/projects/$projectId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdImport
      parentRoute: typeof StaffStaffLayoutImport
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout'
      path: '/projects/$projectId'
      fullPath: '/staff/projects/$projectId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdRoute
    }
    '/proponent/_proponentLayout/_dashboard/projects/': {
      id: '/proponent/_proponentLayout/_dashboard/projects/'
      path: '/projects'
      fullPath: '/proponent/projects'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardProjectsIndexImport
      parentRoute: typeof ProponentProponentLayoutDashboardImport
    }
    '/proponent/_proponentLayout/_dashboard/projects/$projectId': {
      id: '/proponent/_proponentLayout/_dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/proponent/projects/$projectId'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdImport
      parentRoute: typeof ProponentProponentLayoutDashboardImport
    }
    '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout': {
      id: '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout'
      path: '/projects/$projectId'
      fullPath: '/proponent/projects/$projectId'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutImport
      parentRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdRoute
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/'
      path: '/'
      fullPath: '/staff/projects/$projectId/'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutIndexImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutImport
    }
    '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/new-submission': {
      id: '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/new-submission'
      path: '/new-submission'
      fullPath: '/proponent/projects/$projectId/new-submission'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutNewSubmissionImport
      parentRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutImport
    }
    '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/': {
      id: '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/'
      path: '/'
      fullPath: '/proponent/projects/$projectId/'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutIndexImport
      parentRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutImport
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutImport
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute
    }
    '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId': {
      id: '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport
      parentRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutImport
    }
    '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': {
      id: '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
      parentRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
      path: '/'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId/'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
    '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': {
      id: '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
      path: '/'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId/'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport
      parentRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
    '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': {
      id: '/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
      preLoaderRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport
      parentRoute: typeof ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ErrorRoute,
  NotFoundRoute,
  ProponentRoute: ProponentRoute.addChildren({
    ProponentProponentLayoutRoute: ProponentProponentLayoutRoute.addChildren({
      ProponentProponentLayoutDashboardRoute:
        ProponentProponentLayoutDashboardRoute.addChildren({
          ProponentProponentLayoutDashboardProfileRoute,
          ProponentProponentLayoutDashboardAboutpageLazyRoute,
          ProponentProponentLayoutDashboardProjectsIndexRoute,
          ProponentProponentLayoutDashboardProjectsProjectIdRoute:
            ProponentProponentLayoutDashboardProjectsProjectIdRoute.addChildren(
              {
                ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutRoute:
                  ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutRoute.addChildren(
                    {
                      ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutNewSubmissionRoute,
                      ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutIndexRoute,
                      ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute:
                        ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute.addChildren(
                          {
                            ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute:
                              ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute.addChildren(
                                {
                                  ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute,
                                  ProponentProponentLayoutDashboardProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute,
                                },
                              ),
                          },
                        ),
                    },
                  ),
              },
            ),
        }),
      ProponentProponentLayoutAdminLoginRoute,
    }),
    ProponentRegistrationCompleteRoute,
    ProponentRegistrationCreateAccountRoute,
    ProponentRegistrationIndexRoute,
  }),
  StaffRoute: StaffRoute.addChildren({
    StaffStaffLayoutRoute: StaffStaffLayoutRoute.addChildren({
      StaffStaffLayoutProjectsIndexRoute,
      StaffStaffLayoutProjectsProjectIdRoute:
        StaffStaffLayoutProjectsProjectIdRoute.addChildren({
          StaffStaffLayoutProjectsProjectIdProjectLayoutRoute:
            StaffStaffLayoutProjectsProjectIdProjectLayoutRoute.addChildren({
              StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute,
              StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute:
                StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute.addChildren(
                  {
                    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute:
                      StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute.addChildren(
                        {
                          StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute,
                          StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute,
                        },
                      ),
                  },
                ),
            }),
        }),
    }),
  }),
  OidcCallbackIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/error",
        "/not-found",
        "/proponent",
        "/staff",
        "/oidc-callback/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/proponent": {
      "filePath": "proponent",
      "children": [
        "/proponent/_proponentLayout",
        "/proponent/registration/complete",
        "/proponent/registration/create-account",
        "/proponent/registration/"
      ]
    },
    "/proponent/_proponentLayout": {
      "filePath": "proponent/_proponentLayout.tsx",
      "parent": "/proponent",
      "children": [
        "/proponent/_proponentLayout/_dashboard",
        "/proponent/_proponentLayout/admin-login"
      ]
    },
    "/staff": {
      "filePath": "staff",
      "children": [
        "/staff/_staffLayout"
      ]
    },
    "/staff/_staffLayout": {
      "filePath": "staff/_staffLayout.tsx",
      "parent": "/staff",
      "children": [
        "/staff/_staffLayout/projects/",
        "/staff/_staffLayout/projects/$projectId"
      ]
    },
    "/oidc-callback/": {
      "filePath": "oidc-callback/index.tsx"
    },
    "/proponent/_proponentLayout/_dashboard": {
      "filePath": "proponent/_proponentLayout/_dashboard.tsx",
      "parent": "/proponent/_proponentLayout",
      "children": [
        "/proponent/_proponentLayout/_dashboard/profile",
        "/proponent/_proponentLayout/_dashboard/aboutpage",
        "/proponent/_proponentLayout/_dashboard/projects/",
        "/proponent/_proponentLayout/_dashboard/projects/$projectId"
      ]
    },
    "/proponent/_proponentLayout/admin-login": {
      "filePath": "proponent/_proponentLayout/admin-login.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/proponent/registration/complete": {
      "filePath": "proponent/registration/complete.tsx",
      "parent": "/proponent"
    },
    "/proponent/registration/create-account": {
      "filePath": "proponent/registration/create-account.tsx",
      "parent": "/proponent"
    },
    "/proponent/registration/": {
      "filePath": "proponent/registration/index.tsx",
      "parent": "/proponent"
    },
    "/proponent/_proponentLayout/_dashboard/profile": {
      "filePath": "proponent/_proponentLayout/_dashboard/profile.tsx",
      "parent": "/proponent/_proponentLayout/_dashboard"
    },
    "/proponent/_proponentLayout/_dashboard/aboutpage": {
      "filePath": "proponent/_proponentLayout/_dashboard/aboutpage.lazy.tsx",
      "parent": "/proponent/_proponentLayout/_dashboard"
    },
    "/staff/_staffLayout/projects/": {
      "filePath": "staff/_staffLayout/projects/index.tsx",
      "parent": "/staff/_staffLayout"
    },
    "/staff/_staffLayout/projects/$projectId": {
      "filePath": "staff/_staffLayout/projects/$projectId",
      "parent": "/staff/_staffLayout",
      "children": [
        "/staff/_staffLayout/projects/$projectId/_projectLayout"
      ]
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout.tsx",
      "parent": "/staff/_staffLayout/projects/$projectId",
      "children": [
        "/staff/_staffLayout/projects/$projectId/_projectLayout/",
        "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId"
      ]
    },
    "/proponent/_proponentLayout/_dashboard/projects/": {
      "filePath": "proponent/_proponentLayout/_dashboard/projects/index.tsx",
      "parent": "/proponent/_proponentLayout/_dashboard"
    },
    "/proponent/_proponentLayout/_dashboard/projects/$projectId": {
      "filePath": "proponent/_proponentLayout/_dashboard/projects/$projectId",
      "parent": "/proponent/_proponentLayout/_dashboard",
      "children": [
        "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout"
      ]
    },
    "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout": {
      "filePath": "proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout.tsx",
      "parent": "/proponent/_proponentLayout/_dashboard/projects/$projectId",
      "children": [
        "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/new-submission",
        "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/",
        "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId"
      ]
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout/": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout/index.tsx",
      "parent": "/staff/_staffLayout/projects/$projectId/_projectLayout"
    },
    "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/new-submission": {
      "filePath": "proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/new-submission.tsx",
      "parent": "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout"
    },
    "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/": {
      "filePath": "proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/index.tsx",
      "parent": "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout"
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "parent": "/staff/_staffLayout/projects/$projectId/_projectLayout",
      "children": [
        "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
      ]
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout.tsx",
      "parent": "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "children": [
        "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/",
        "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId"
      ]
    },
    "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId": {
      "filePath": "proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "parent": "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout",
      "children": [
        "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
      ]
    },
    "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout": {
      "filePath": "proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout.tsx",
      "parent": "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "children": [
        "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/",
        "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId"
      ]
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index.tsx",
      "parent": "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId.tsx",
      "parent": "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    },
    "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/": {
      "filePath": "proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index.tsx",
      "parent": "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    },
    "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId": {
      "filePath": "proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId.tsx",
      "parent": "/proponent/_proponentLayout/_dashboard/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    }
  }
}
ROUTE_MANIFEST_END */
