app:
  name: submit
  url: https://submit.eao.gov.bc.ca
  api: https://submit-api-c72cba-prod.apps.gold.devops.gov.bc.ca/api
  env: prod
  version: 1.0.0
  title: EPIC.submit
  objectStorageUrl: https://epic-document-api-c8b80a-prod.apps.gold.devops.gov.bc.ca/api
  oidcAuthority: https://loginproxy.gov.bc.ca/auth/realms/eao-epic
  clientId: epic-submit
  conditionsLibraryUrl: https://condition-api-c8b80a-prod.apps.gold.devops.gov.bc.ca/api
  user_guide: /docs/Holder-User-Guide-EPIC.submit-v1.1.pdf
  centreApiUrl: https://centre-api-c8b80a-prod.apps.gold.devops.gov.bc.ca
  geoDocUrl: https://www2.gov.bc.ca/assets/download/C92C40FD8897448F916AB4FE518A4539
  epicSystemEmail: EAO.EPICsystem@gov.bc.ca
  supportMpEmail: EAO.ManagementPlanSupport@gov.bc.ca
  supportIpdEmail: EAO.emailaddress@gov.bc.ca

resources:
  cpu:
    limit: 200m
    request: 200m
  memory:
    limit: 200Mi
    request: 100Mi

image:
  name: submit-web
  tag: prod
  repository: image-registry.openshift-image-registry.svc:5000/c72cba-tools/

keycloak:
  url: "https://loginproxy.gov.bc.ca"
  realm: eao-epic
  client: epic-submit

service:
  port: 8080

replicas:
  count: 2

mountPath: /usr/share/nginx/html/config/
