app:
  name: submit
  url: submit-web-{{ .Release.Namespace }}.apps.gold.devops.gov.bc.ca
  api: https://submit-api-{{ .Release.Namespace }}.apps.gold.devops.gov.bc.ca
  env: dev
  version: 1.0.0
  title: EPIC.Submit
  objectStorageUrl: https://epic-document-{{ .Release.Namespace }}.apps.gold.devops.gov.bc.ca/api
  oidcAuthority: https://dev.oidc.gov.bc.ca/auth/realms/eao
  clientId: epic-submit
  conditionsLibraryUrl: https://condition-api-{{ .Release.Namespace }}.gold.devops.gov.bc.ca/api
resources:
  cpu:
    limit: 200m
    request: 200m
  memory:
    limit: 200Mi
    request: 100Mi
image:
  name: submit-web
  tag: latest
  repository: image-registry.openshift-image-registry.svc:5000/c8b80a-tools/
keycloak:
  url: "https://dev.loginproxy.gov.bc.ca"
  realm: eao-epic
  client: submit-web
service:
  port: 8080
replicas:
  count: 1
mountPath: /usr/share/nginx/html/config/

