apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}
data:
  JWT_OIDC_ALGORITHMS: {{ .Values.auth.jwt.alg }}
  JWT_OIDC_AUDIENCE: {{ .Values.auth.jwt.aud }}
  JWT_OIDC_CACHING_ENABLED: "{{ .Values.auth.jwt.cacheEnabled }}"
  JWT_OIDC_ISSUER: {{ .Values.auth.jwt.issuer }}
  JWT_OIDC_JWKS_CACHE_TIMEOUT: "{{ .Values.auth.jwt.cacheTimeout }}"
  JWT_OIDC_WELL_KNOWN_CONFIG: {{ .Values.auth.jwt.wellKnownConfig }}
  PYTHONBUFFERED: "{{ .Values.python.pythonBuffered }}"
  KEYCLOAK_BASE_URL: {{ .Values.auth.keycloak.uri }}
  KEYCLOAK_REALM_NAME: {{ .Values.auth.keycloak.realm }}
  INSTANCE_ADMIN_GROUP: {{ .Values.auth.keycloak.instanceAdminGroup }}
  CONNECT_TIMEOUT: "{{ .Values.python.connectTimeout }}"
  CORS_ORIGIN: "{{ .Values.cors.origin }}"
  BASE_APP_URL: {{ .Values.web.url }}
  BC_SERVICE_CARD_URL: {{ .Values.bcServiceCard.url }}
  LEGISLATIVE_TIMEZONE: {{ .Values.timezone }}
  SENDER_EMAIL: {{ .Values.sender.email }}
  STAFF_SUPPORT_MAIL_ID: {{ .Values.staffSupport.email }}
