{{- if .Values.database.demo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}-{{ .Values.database.demo.suffix }}
  name: {{ .Values.database.secret }}-{{ .Values.database.demo.suffix }}
type: Opaque
stringData:
  app-db-username: {{ .Values.database.demo.username | quote }}
  app-db-password: {{ .Values.database.demo.password | quote }}
  app-db-name: {{ .Values.database.demo.name | quote }}
{{- end }}
