apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}
stringData:
  SERVICE_ACCOUNT_ID: {{ .Values.auth.keycloak.adminClientId }}
  SERVICE_ACCOUNT_SECRET: {{ .Values.auth.keycloak.adminClientSecret }}
