apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
stringData:
  SERVICE_ACCOUNT_ID: {{ .Values.auth.serviceAccount.id }}
  SERVICE_ACCOUNT_SECRET: {{ .Values.auth.serviceAccount.secret }}
