name: SUBMIT WEB CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "submit-web/**"
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/test/prod)"
        required: true
        default: "dev"

defaults:
  run:
    shell: bash
    working-directory: ./submit-web

jobs:
  setup-job:
    runs-on: ubuntu-22.04

    if: github.repository == 'bcgov/EPIC.submit'

    steps:
      - uses: actions/checkout@v2
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Lint
        id: lint
        run: |
          npm run lint

  unit-test:
    needs: setup-job
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Run unit tests
        id: unit-test
        run: |
          npm run test:unit

  build-check:
    needs: setup-job
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      - name: build to check strictness
        id: build
        run: |
          npm run build --quiet || true
