name: SUBMIT WEB CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "submit-web/**"
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash
    working-directory: ./submit-web

jobs:
  setup-job:
    runs-on: ubuntu-20.04

    if: github.repository == 'bcgov/EPIC.submit'

    steps:
      - uses: actions/checkout@v2
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Lint
        id: lint
        run: |
          npm run lint

  testing:
    needs: setup-job
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Print working directory
        run:  |
          echo "Working directory: ${PWD}"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          wait-on: 'http://localhost:3000'
          browser: chrome
          working-directory: ./submit-web
          component: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true

  build-check:
    needs: setup-job
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      - name: build to check strictness
        id: build
        run: |
          npm run build --quiet || true
